#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Copyright (C) 2017 Kalray Inc.
#

extra-y	:= head.o vmlinux.lds

obj-y	:= setup.o process.o traps.o common.o time.o prom.o \
		k1_ksyms.o delay.o irq.o cpuinfo.o ptrace.o \
		entry.o
