/* SPDX-License-Identifier: GPL-2.0 */
/*
 * This file is subject to the terms and conditions of the GNU General Public
 * License.  See the file "COPYING" in the main directory of this archive
 * for more details.
 *
 * Copyright (C) 2019 Kalray Inc.
 */

#ifndef PCIE_K1C_NWL_H
#define PCIE_K1C_NWL_H

/* BAR decoder registers */
#define BAR_DECODER_BYPASS_EN		0x00008014

/* Core config status registers */
#define CSR_MGMT_TLB_BASE		0x00002000
#define CSR_MGMT_PTL_BASE		0x00003000
#define CSR_MGMT_FTL_BASE		0x00004000

#define CSR_TLB_LTSSM_PORT_TYPE	(CSR_MGMT_TLB_BASE+0x00000040)
#define CSR_TLB_LTSSM_RX_DET	(CSR_MGMT_TLB_BASE+0x0000004C)
#define CSR_TLB_DL_STAT		(CSR_MGMT_TLB_BASE+0x00000394)
#define CSR_TLB_DL_INJECT	(CSR_MGMT_TLB_BASE+0x0000039C)
#define CSR_TLB_DLLP_INJECT	(CSR_MGMT_TLB_BASE+0x000003A0)

#define CSR_FTL_DECODE_T1	(CSR_MGMT_FTL_BASE+0x00000014)
#define CSR_FTL_INITIAL		(CSR_MGMT_FTL_BASE+0x00000020)
#define CSR_FTL_CFG		(CSR_MGMT_FTL_BASE+0x00000030)
#define CSR_FTL_ID3		(CSR_MGMT_FTL_BASE+0x00000048)
#define CSR_FTL_PCIE_CAP	(CSR_MGMT_FTL_BASE+0x00000080)
#define CSR_FTL_SLOT_CAP	(CSR_MGMT_FTL_BASE+0x00000090)
#define CSR_FTL_ARI_CAP		(CSR_MGMT_FTL_BASE+0x000000E0)
#define CSR_FTL_MSI_CAP		(CSR_MGMT_FTL_BASE+0x000000E8)
#define CSR_FTL_MSIX_CAP	(CSR_MGMT_FTL_BASE+0x000000F0)
#define CSR_FTL_AER_CAP		(CSR_MGMT_FTL_BASE+0x00000100)

/* Pcie capabilities */
#define CSR_FTL_CAP_SLOT_IMPLEMENTED_SHIFT         0x8
#define CSR_FTL_CAP_SLOT_IMPLEMENTED_MASK          0x100UL
#define CSR_FTL_CAP_DEVICE_PORT_TYPE_SHIFT         0x4
#define CSR_FTL_CAP_DEVICE_PORT_TYPE_MASK          0xF0UL

/* LTSSM properties */
#define CSR_TLB_LTSSM_PORT_TYPE_DS_US_N_SHIFT 0x0
#define CSR_TLB_LTSSM_PORT_TYPE_DS_US_N_MASK  0x1UL
#define CSR_TLB_LTSSM_RX_DET_MASK_SHIFT     0x0
#define CSR_TLB_LTSSM_RX_DET_MASK_MASK      0xFFFFUL
#define CSR_TLB_LTSSM_RX_DET_OVERRIDE_SHIFT 0x1f
#define CSR_TLB_LTSSM_RX_DET_OVERRIDE_MASK  0x80000000UL
#define CSR_TLB_LTSSM_DL_LINK_UP_SHIFT                      0x1f
#define CSR_TLB_LTSSM_DL_LINK_UP_MASK                       0x80000000UL
#define CSR_TLB_LTSSM_PL_LINK_UP_SHIFT                      0x1e
#define CSR_TLB_LTSSM_PL_LINK_UP_MASK                       0x40000000UL

/* Pcie ftl capabilities */
#define CSR_FTL_CFG_TYPE1_TYPE0_N_SHIFT 0x0
#define CSR_FTL_CFG_TYPE1_TYPE0_N_MASK  0x1UL
#define CSR_FTL_DECODE_T1_RX_BYPASS_MSG_DEC_SHIFT 0x8
#define CSR_FTL_DECODE_T1_RX_BYPASS_MSG_DEC_MASK  0x100UL
#define CSR_FTL_ARI_CAP_DISABLE_SHIFT 0x0
#define CSR_FTL_ARI_CAP_DISABLE_MASK  0x1UL
#define CSR_FTL_ID3_CLASS_CODE_SHIFT  0x8
#define CSR_FTL_ID3_CLASS_CODE_MASK   0xFFFFFF00UL
#define CSR_FTL_MSI_CAP_DISABLE_SHIFT              0x0
#define CSR_FTL_MSI_CAP_DISABLE_MASK               0x1UL
#define CSR_FTL_MSI_CAP_MULT_MESSAGE_CAPABLE_SHIFT 0x4
#define CSR_FTL_MSI_CAP_MULT_MESSAGE_CAPABLE_MASK  0x70UL
#define CSR_FTL_MSIX_CAP_DISABLE_SHIFT    0x0
#define CSR_FTL_MSIX_CAP_DISABLE_MASK     0x1UL
#define CSR_FTL_MSIX_CAP_TABLE_SIZE_SHIFT 0x10
#define CSR_FTL_MSIX_CAP_TABLE_SIZE_MASK  0x7FF0000UL
#define CSR_FTL_AER_CAP_V2_SHIFT			 0x0
#define CSR_FTL_AER_CAP_V2_MASK				 0x1UL
#define CSR_FTL_AER_CAP_ECRC_GEN_CHK_CAPABLE_SHIFT       0x1
#define CSR_FTL_AER_CAP_ECRC_GEN_CHK_CAPABLE_MASK        0x2UL
#define CSR_FTL_AER_CAP_EN_CORR_INTERNAL_ERROR_SHIFT     0x16
#define CSR_FTL_AER_CAP_EN_CORR_INTERNAL_ERROR_MASK      0x400000UL
#define CSR_FTL_AER_CAP_EN_COMPLETION_TIMEOUT_SHIFT      0x18
#define CSR_FTL_AER_CAP_EN_COMPLETION_TIMEOUT_MASK       0x1000000UL
#define CSR_FTL_AER_CAP_EN_COMPLETER_ABORT_SHIFT         0x19
#define CSR_FTL_AER_CAP_EN_COMPLETER_ABORT_MASK          0x2000000UL
#define CSR_FTL_AER_CAP_EN_RECEIVER_OVERFLOW_SHIFT       0x1a
#define CSR_FTL_AER_CAP_EN_RECEIVER_OVERFLOW_MASK        0x4000000UL
#define CSR_FTL_AER_CAP_EN_ACS_VIOLATION_SHIFT           0x1b
#define CSR_FTL_AER_CAP_EN_ACS_VIOLATION_MASK            0x8000000UL
#define CSR_FTL_AER_CAP_EN_UCORR_INTERNAL_ERROR_SHIFT    0x1c
#define CSR_FTL_AER_CAP_EN_UCORR_INTERNAL_ERROR_MASK     0x10000000UL
#define CSR_FTL_AER_CAP_EN_MC_BLOCKED_TLP_SHIFT          0x1d
#define CSR_FTL_AER_CAP_EN_MC_BLOCKED_TLP_MASK           0x20000000UL
#define CSR_FTL_AER_CAP_EN_ATOMICOP_EGRESS_BLOCKED_SHIFT 0x1e
#define CSR_FTL_AER_CAP_EN_ATOMICOP_EGRESS_BLOCKED_MASK  0x40000000UL
#define CSR_FTL_AER_CAP_EN_SURPRISE_DOWN_ERROR_SHIFT     0x17
#define CSR_FTL_AER_CAP_EN_SURPRISE_DOWN_ERROR_MASK      0x800000UL
#define CSR_FTL_AER_CAP_EN_TLP_PREFIX_BLOCKED_SHIFT      0x1f
#define CSR_FTL_AER_CAP_EN_TLP_PREFIX_BLOCKED_MASK       0x80000000UL
#define CSR_FTL_MAX_LINK_WIDTH_SHIFT    0x10
#define CSR_FTL_MAX_LINK_WIDTH_MASK     0x70000UL

/* SLOT capabilities */
#define CSR_FTL_SLOT_CAP_ATTENTION_BUTTON_PRESENT_SHIFT     0x0
#define CSR_FTL_SLOT_CAP_ATTENTION_BUTTON_PRESENT_MASK      0x1UL
#define CSR_FTL_SLOT_CAP_MRL_SENSOR_PRESENT_SHIFT           0x2
#define CSR_FTL_SLOT_CAP_MRL_SENSOR_PRESENT_MASK            0x4UL
#define CSR_FTL_SLOT_CAP_ATTENTION_INDICATOR_PRESENT_SHIFT  0x3
#define CSR_FTL_SLOT_CAP_ATTENTION_INDICATOR_PRESENT_MASK   0x8UL
#define CSR_FTL_SLOT_CAP_POWER_INDICATOR_PRESENT_SHIFT      0x4
#define CSR_FTL_SLOT_CAP_POWER_INDICATOR_PRESENT_MASK       0x10UL
#define CSR_FTL_SLOT_CAP_HOT_PLUG_SURPRISE_SHIFT            0x5
#define CSR_FTL_SLOT_CAP_HOT_PLUG_SURPRISE_MASK             0x20UL
#define CSR_FTL_SLOT_CAP_HOT_PLUG_CAPABLE_SHIFT             0x6
#define CSR_FTL_SLOT_CAP_HOT_PLUG_CAPABLE_MASK              0x40UL
#define CSR_FTL_SLOT_CAP_SLOT_POWER_LIMIT_VALUE_SHIFT       0x7
#define CSR_FTL_SLOT_CAP_SLOT_POWER_LIMIT_VALUE_MASK        0x7F80UL
#define CSR_FTL_SLOT_CAP_SLOT_POWER_LIMIT_SCALE_SHIFT       0xf
#define CSR_FTL_SLOT_CAP_SLOT_POWER_LIMIT_SCALE_MASK        0x18000UL
#define CSR_FTL_SLOT_CAP_EM_INTERLOCK_PRESENT_SHIFT         0x11
#define CSR_FTL_SLOT_CAP_EM_INTERLOCK_PRESENT_MASK          0x20000UL
#define CSR_FTL_SLOT_CAP_NO_COMMAND_COMPLETED_SUPPORT_SHIFT 0x12
#define CSR_FTL_SLOT_CAP_NO_COMMAND_COMPLETED_SUPPORT_MASK  0x40000UL
#define CSR_FTL_SLOT_CAP_PHYSICAL_SLOT_NUMBER_SHIFT         0x13
#define CSR_FTL_SLOT_CAP_PHYSICAL_SLOT_NUMBER_MASK          0xFFF80000UL


#endif /* PCIE_K1C_NWL_H */
