# UAPI Header export list
include include/uapi/asm-generic/Kbuild.asm

generic-y += auxvec.h
generic-y += byteorder.h
generic-y += errno.h
generic-y += ipcbuf.h
generic-y += mman.h
generic-y += msgbuf.h
generic-y += param.h
generic-y += sembuf.h
generic-y += shmbuf.h
generic-y += siginfo.h
generic-y += socket.h
generic-y += sockios.h
generic-y += stat.h
generic-y += statfs.h
generic-y += swab.h
generic-y += types.h
generic-y += unistd.h
