/* SPDX-License-Identifier: GPL-2.0 */
/*
 * This file is subject to the terms and conditions of the GNU General Public
 * License.  See the file "COPYING" in the main directory of this archive
 * for more details.
 *
 * Copyright (C) 2019 Kalray Inc.
 */

#ifndef ASM_K1C_DMA_REGS_H
#define ASM_K1C_DMA_REGS_H

#define K1C_DMA_RX_CHANNEL_NUMBER            (64)
#define K1C_DMA_RX_JOB_QUEUE_NUMBER          (8)
#define K1C_DMA_RX_JOB_CACHE_NUMBER          (4)
#define K1C_DMA_TX_THREAD_NUMBER             (4)
#define K1C_DMA_TX_PGRM_MEM_NUMBER           (128)
#define K1C_DMA_TX_PGRM_TABLE_NUMBER         (16)
#define K1C_DMA_NOC_ROUTE_TABLE_NUMBER       (512)
#define K1C_DMA_BW_LIMITER_TABLE_NUMBER      (16)
#define K1C_DMA_TX_JOB_QUEUE_NUMBER          (64)
#define K1C_DMA_TX_COMPLETION_QUEUE_NUMBER   (64)
#define K1C_DMA_TX_PGRM_MEM_NUMBER           (128)
#define K1C_DMA_TX_PGRM_TAB_NUMBER           (16)

/* RX channels */
#define K1C_DMA_RX_CHAN_OFFSET 0x0
#define K1C_DMA_RX_CHAN_ELEM_SIZE 0x1000
#define K1C_DMA_RX_CHAN_BUF_SA_OFFSET     0x0
#define K1C_DMA_RX_CHAN_BUF_SIZE_OFFSET     0x8
#define K1C_DMA_RX_CHAN_BUF_EN_OFFSET     0x10
#define K1C_DMA_RX_CHAN_CUR_OFFSET     0x18
#define K1C_DMA_RX_CHAN_CUR_OFFSET_SHIFT 0x0
#define K1C_DMA_RX_CHAN_CUR_OFFSET_MASK  0x1FFFFFFFFFF
#define K1C_DMA_RX_CHAN_JOB_Q_CFG_OFFSET     0x20
#define K1C_DMA_RX_CHAN_ACTIVATED_OFFSET     0x28
#define K1C_DMA_RX_CHAN_BYTE_CNT_OFFSET     0x30
#define K1C_DMA_RX_CHAN_NOTIF_CNT_OFFSET     0x38
#define K1C_DMA_RX_CHAN_CNT_CLEAR_MODE_OFFSET     0x40
#define K1C_DMA_RX_CHAN_COMP_Q_CFG_OFFSET     0x58
#define K1C_DMA_RX_CHAN_COMP_Q_MODE_OFFSET     0x60
#define K1C_DMA_RX_CHAN_COMP_Q_SA_OFFSET     0x68
#define K1C_DMA_RX_CHAN_COMP_Q_SLOT_NB_LOG2_OFFSET     0x70
#define K1C_DMA_RX_CHAN_COMP_Q_WP_OFFSET     0x78
#define K1C_DMA_RX_CHAN_COMP_Q_RP_OFFSET     0x80
#define K1C_DMA_RX_CHAN_COMP_Q_LOAD_INCR_RP_OFFSET     0x88
#define K1C_DMA_RX_CHAN_COMP_Q_VALID_RP_OFFSET     0x90
#define K1C_DMA_RX_CHAN_COMP_Q_NOTIF_ADDR_OFFSET     0xA0
#define K1C_DMA_RX_CHAN_COMP_Q_FULL_NOTIF_ADDR_OFFSET     0xA8
#define K1C_DMA_RX_CHAN_COMP_Q_NOTIF_ARG_OFFSET     0xB0
#define K1C_DMA_RX_CHAN_COMP_Q_ASN_OFFSET     0xB8

/* RX job queues */
#define K1C_DMA_RX_JOB_Q_OFFSET 0x40000
#define K1C_DMA_RX_JOB_Q_ELEM_SIZE 0x1000
#define K1C_DMA_RX_JOB_Q_SA_OFFSET     0x0
#define K1C_DMA_RX_JOB_Q_NB_LOG2_OFFSET     0x8
#define K1C_DMA_RX_JOB_Q_WP_OFFSET     0x10
#define K1C_DMA_RX_JOB_Q_LOAD_INCR_WP_OFFSET     0x18
#define K1C_DMA_RX_JOB_Q_VALID_WP_OFFSET     0x20
#define K1C_DMA_RX_JOB_Q_LOAD_INCR_VALID_WP_OFFSET     0x28
#define K1C_DMA_RX_JOB_Q_RP_OFFSET     0x30
#define K1C_DMA_RX_JOB_Q_NOTIF_ADDR_OFFSET     0x38
#define K1C_DMA_RX_JOB_Q_NOTIF_ARG_OFFSET     0x40
#define K1C_DMA_RX_JOB_Q_NOTIF_MODE_OFFSET     0x48
#define K1C_DMA_RX_JOB_Q_STOP_OFFSET     0x58
#define K1C_DMA_RX_JOB_Q_ACTIVATE_OFFSET     0x50
#define K1C_DMA_RX_JOB_Q_STATUS_OFFSET     0x60
#define K1C_DMA_RX_JOB_Q_CACHE_ID_OFFSET     0x70
#define K1C_DMA_RX_JOB_Q_ASN_OFFSET     0x78

/* TX job queues */
#define K1C_DMA_TX_JOB_Q_OFFSET 0x80000
#define K1C_DMA_TX_JOB_Q_ELEM_SIZE 0x1000
#define K1C_DMA_TX_JOB_Q_SA_OFFSET     0x0
#define K1C_DMA_TX_JOB_Q_NB_LOG2_OFFSET     0x8
#define K1C_DMA_TX_JOB_Q_WP_OFFSET     0x10
#define K1C_DMA_TX_JOB_Q_LOAD_INCR_WP_OFFSET     0x18
#define K1C_DMA_TX_JOB_Q_VALID_WP_OFFSET     0x20
#define K1C_DMA_TX_JOB_Q_RP_OFFSET     0x30
#define K1C_DMA_TX_JOB_Q_NOTIF_ADDR_OFFSET     0x38
#define K1C_DMA_TX_JOB_Q_NOTIF_ARG_OFFSET     0x40
#define K1C_DMA_TX_JOB_Q_ASN_OFFSET     0x48
#define K1C_DMA_TX_JOB_Q_STATUS_OFFSET     0x50
#define K1C_DMA_TX_JOB_Q_STOP_OFFSET     0x68
#define K1C_DMA_TX_JOB_Q_ACTIVATE_OFFSET     0x60
#define K1C_DMA_TX_JOB_Q_THREAD_ID_OFFSET     0x70
#define K1C_DMA_TX_JOB_Q_ON_GOING_JOB_CNT_OFFSET     0x78

/* TX completion queues */
#define K1C_DMA_TX_COMP_Q_OFFSET 0xC0000
#define K1C_DMA_TX_COMP_Q_ELEM_SIZE 0x1000
#define K1C_DMA_TX_COMP_Q_MODE_OFFSET     0x0
#define K1C_DMA_TX_COMP_Q_SA_OFFSET     0x8
#define K1C_DMA_TX_COMP_Q_NB_LOG2_OFFSET     0x10
#define K1C_DMA_TX_COMP_Q_GLOBAL_OFFSET     0x18
#define K1C_DMA_TX_COMP_Q_ASN_OFFSET     0x20
#define K1C_DMA_TX_COMP_Q_FIELD_EN_OFFSET     0x28
#define K1C_DMA_TX_COMP_Q_WP_OFFSET     0x30
#define K1C_DMA_TX_COMP_Q_RP_OFFSET     0x40
#define K1C_DMA_TX_COMP_Q_LOAD_INCR_RP_OFFSET     0x48
#define K1C_DMA_TX_COMP_Q_VALID_RP_OFFSET     0x50
#define K1C_DMA_TX_COMP_Q_LOAD_INCR_VALID_RP_OFFSET     0x58
#define K1C_DMA_TX_COMP_Q_NOTIF_ADDR_OFFSET     0x60
#define K1C_DMA_TX_COMP_Q_NOTIF_ARG_OFFSET     0x68
#define K1C_DMA_TX_COMP_Q_ACTIVATE_OFFSET     0x70
#define K1C_DMA_TX_COMP_Q_STOP_OFFSET     0x78
#define K1C_DMA_TX_COMP_Q_STATUS_OFFSET     0x80

/* DMA IT vector */
#define K1C_DMA_IT_OFFSET 0x50000
#define K1C_DMA_IT_EN_OFFSET     0x0
#define K1C_DMA_IT_VECTOR_OFFSET     0x10
#define K1C_DMA_IT_VECTOR_LAC_OFFSET     0x18

/* DMA error status */
#define K1C_DMA_ERROR_OFFSET 0x51000
#define K1C_DMA_ERROR_RX_CHAN_STATUS_OFFSET     0x0
#define K1C_DMA_ERROR_RX_JOB_STATUS_OFFSET     0x10
#define K1C_DMA_ERROR_TX_JOB_STATUS_OFFSET     0x20
#define K1C_DMA_ERROR_TX_THREAD_STATUS_OFFSET     0x30
#define K1C_DMA_ERROR_TX_COMP_STATUS_OFFSET     0x40

/* TX thread */
#define K1C_DMA_TX_THREAD_OFFSET 0x60000
#define K1C_DMA_TX_THREAD_ELEM_SIZE 0x1000
#define K1C_DMA_TX_THREAD_ERROR_OFFSET     0x70

/* NOC route table */
#define K1C_DMA_NOC_RT_OFFSET     0x66000
#define K1C_DMA_NOC_RT_ELEM_SIZE  0x8
#define K1C_DMA_NOC_RT_NOC_ROUTE_SHIFT 0x0
#define K1C_DMA_NOC_RT_NOC_ROUTE_MASK  0xFFFFFFFFFF
#define K1C_DMA_NOC_RT_RX_TAG_SHIFT    0x28
#define K1C_DMA_NOC_RT_RX_TAG_MASK     0x3F0000000000
#define K1C_DMA_NOC_RT_QOS_ID_SHIFT    0x2e
#define K1C_DMA_NOC_RT_QOS_ID_MASK     0x3C00000000000
#define K1C_DMA_NOC_RT_GLOBAL_SHIFT    0x32
#define K1C_DMA_NOC_RT_GLOBAL_MASK     0x4000000000000
#define K1C_DMA_NOC_RT_ASN_SHIFT       0x33
#define K1C_DMA_NOC_RT_ASN_MASK        0xFF8000000000000
#define K1C_DMA_NOC_RT_VCHAN_SHIFT     0x3c
#define K1C_DMA_NOC_RT_VCHAN_MASK      0x1000000000000000
#define K1C_DMA_NOC_RT_VALID_SHIFT     0x3d
#define K1C_DMA_NOC_RT_VALID_MASK      0x2000000000000000

/* Program table */
#define K1C_DMA_TX_PGRM_TAB_OFFSET     0x65000
#define K1C_DMA_TX_PGRM_TAB_TRANSFER_MODE_SHIFT 0x7
#define K1C_DMA_TX_PGRM_TAB_TRANSFER_MODE_MASK  0x80
#define K1C_DMA_TX_PGRM_TAB_PM_START_ADDR_SHIFT 0x0
#define K1C_DMA_TX_PGRM_TAB_PM_START_ADDR_MASK  0x7F
#define K1C_DMA_TX_PGRM_TAB_GLOBAL_SHIFT        0x8
#define K1C_DMA_TX_PGRM_TAB_GLOBAL_MASK         0x100
#define K1C_DMA_TX_PGRM_TAB_ASN_SHIFT           0x9
#define K1C_DMA_TX_PGRM_TAB_ASN_MASK            0x3FE00
#define K1C_DMA_TX_PGRM_TAB_VALID_SHIFT         0x12
#define K1C_DMA_TX_PGRM_TAB_VALID_MASK          0x40000

/* Program memory */
#define K1C_DMA_TX_PGRM_MEM_OFFSET     0x64000

#endif /* ASM_K1C_DMA_REGS_H */
