obj-$(CONFIG_K1C_DMA_NOC) += k1c-dma.o k1c-dma-hw.o k1c-dma-ucode.o k1c-irqs.o k1c-dma-fs.o

obj-$(CONFIG_K1C_DMA_NOC_TEST) += k1c_dma_noc_test.o
k1c_dma_noc_test-objs := k1c-test.o test_mem2dev.o test_mem2mem.o test_mem2noc.o
