#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Copyright (C) 2017 Kalray Inc.
#

lib-y := usercopy.o clear_page.o copy_page.o memcpy.o memset.o strlen.o delay.o
