/* SPDX-License-Identifier: GPL-2.0 */
/*
 * This file is subject to the terms and conditions of the GNU General Public
 * License.  See the file "COPYING" in the main directory of this archive
 * for more details.
 *
 * Copyright (C) 2019 Kalray Inc.
 */

#ifndef ASM_KVX_MAC_REGS_H
#define ASM_KVX_MAC_REGS_H

/* MAC */
#define MAC_RESET_OFFSET                           0x6020
#define MAC_RESET_CLEAR_OFFSET                     0x6028
#define MAC_1MS_DIV_OFFSET                         0x60E0
#define MAC_BYPASS_OFFSET                          0x6000
#define MAC_BYPASS_ETH_LOOPBACK_SHIFT              0x0
#define MAC_BYPASS_ETH_LOOPBACK_MASK               0x1UL
#define MAC_BYPASS_MAC_LOOPBACK_SHIFT              0x1
#define MAC_BYPASS_MAC_LOOPBACK_MASK               0x2UL
#define MAC_BYPASS_LOOPBACK_LATENCY_SHIFT          0x2
#define MAC_BYPASS_LOOPBACK_LATENCY_MASK           0x1CUL
#define MAC_BYPASS_MAC_OUT_LOOPBACK_SHIFT          0x5
#define MAC_BYPASS_MAC_OUT_LOOPBACK_MASK           0x1E0UL
#define MAC_FCS_OFFSET                             0x6004
#define MAC_FCS_EN_SHIFT                           0x0
#define MAC_FCS_EN_MASK                            0xFUL
#define MAC_MODE_OFFSET                            0x60C4
#define MAC_PCS100_EN_IN_SHIFT                     0x4
#define MAC_PCS100_EN_IN_MASK                      0x10UL
#define MAC_MODE40_EN_IN_SHIFT                     0x5
#define MAC_MODE40_EN_IN_MASK                      0x20UL
#define MAC_SG_OFFSET                              0x60CC
#define MAC_SG_EN_SHIFT                            0x0
#define MAC_SG_EN_MASK                             0xFUL
#define MAC_SG_TX_LANE_CKMULT_SHIFT                0x4
#define MAC_SG_TX_LANE_CKMULT_MASK                 0x70UL
#define MAC_SG_STATUS_OFFSET                       0x60D0
#define MAC_FEC_CTRL_OFFSET                        0x6034
#define MAC_FEC_CTRL_FEC_EN_SHIFT                  0x0
#define MAC_FEC_CTRL_FEC_EN_MASK                   0xFUL
#define MAC_FEC91_CTRL_OFFSET                      0x60C0
#define MAC_FEC91_ENA_IN_SHIFT                     0x0
#define MAC_FEC91_ENA_IN_MASK                      0xFUL
#define MAC_TX_FAULT_CTRL_OFFSET                   0x60D4
#define MAC_FAULT_STATUS_OFFSET                    0x60D8
#define MAC_SYNC_STATUS_OFFSET                     0x602C
#define MAC_SYNC_STATUS_LINK_STATUS_SHIFT          0x19
#define MAC_SYNC_STATUS_LINK_STATUS_MASK           0x1E000000UL
#define MAC_RS_FEC_STATUS_OFFSET                   0x6030
#define MAC_RS_FEC_STATUS_BLOCK_LOCK_SHIFT         0x0
#define MAC_RS_FEC_STATUS_BLOCK_LOCK_MASK          0xFUL
#define MAC_RS_FEC_STATUS_ALIGNED_SHIFT            0x4
#define MAC_RS_FEC_STATUS_ALIGNED_MASK             0xF0UL
#define MAC_FEC_STATUS_OFFSET                      0x6038
#define MAC_CTRL_OFFSET                            0x2400
#define MAC_CTRL_ELEM_SIZE                         0x200

/* MAC_1G */
#define MAC_1G_MODE_OFFSET                         0x50
#define MAC_1G_MODE_SGMII_EN_SHIFT                 0x0
#define MAC_1G_MODE_SGMII_EN_MASK                  0x1UL
#define MAC_1G_MODE_USE_SGMII_AN_SHIFT             0x1
#define MAC_1G_MODE_USE_SGMII_AN_MASK              0x2UL
#define MAC_1G_MODE_SGMII_SPEED_SHIFT              0x2
#define MAC_1G_MODE_SGMII_SPEED_MASK               0xCUL
#define MAC_1G_MODE_SGMII_DUPLEX_SHIFT             0x4
#define MAC_1G_MODE_SGMII_DUPLEX_MASK              0x10UL
#define MAC_1G_OFFSET                              0x3200
#define MAC_1G_ELEM_SIZE                           0x80
#define MAC_1G_CTRL_OFFSET                         0x0
#define MAC_1G_CTRL_SPEED_SEL_LSB_SHIFT            0x6
#define MAC_1G_CTRL_SPEED_SEL_LSB_MASK             0x40UL
#define MAC_1G_CTRL_SPEED_SEL_MSB_SHIFT            0xd
#define MAC_1G_CTRL_SPEED_SEL_MSB_MASK             0x2000UL
#define MAC_1G_CTRL_COLLISION_TEST_SHIFT           0x7
#define MAC_1G_CTRL_COLLISION_TEST_MASK            0x80UL
#define MAC_1G_CTRL_DUPLEX_MODE_SHIFT              0x8
#define MAC_1G_CTRL_DUPLEX_MODE_MASK               0x100UL
#define MAC_1G_CTRL_RESTART_AN_SHIFT               0x9
#define MAC_1G_CTRL_RESTART_AN_MASK                0x200UL
#define MAC_1G_CTRL_AN_EN_SHIFT                    0xc
#define MAC_1G_CTRL_AN_EN_MASK                     0x1000UL
#define MAC_1G_CTRL_LOOPBACK_SHIFT                 0xe
#define MAC_1G_CTRL_LOOPBACK_MASK                  0x4000UL
#define MAC_1G_CTRL_RESET_SHIFT                    0xf
#define MAC_1G_CTRL_RESET_MASK                     0x8000UL
#define MAC_1G_STATUS_OFFSET                       0x4
#define MAC_1G_STATUS_EXT_CAP_SHIFT                0x0
#define MAC_1G_STATUS_EXT_CAP_MASK                 0x1UL
#define MAC_1G_STATUS_JABBER_DETECT_SHIFT          0x1
#define MAC_1G_STATUS_JABBER_DETECT_MASK           0x2UL
#define MAC_1G_STATUS_LINK_STATUS_SHIFT            0x2
#define MAC_1G_STATUS_LINK_STATUS_MASK             0x4UL
#define MAC_1G_STATUS_AN_ABILITY_SHIFT             0x3
#define MAC_1G_STATUS_AN_ABILITY_MASK              0x8UL
#define MAC_1G_STATUS_REMOTE_FAULT_SHIFT           0x4
#define MAC_1G_STATUS_REMOTE_FAULT_MASK            0x10UL
#define MAC_1G_STATUS_AN_COMPLETE_SHIFT            0x5
#define MAC_1G_STATUS_AN_COMPLETE_MASK             0x20UL
#define MAC_1G_STATUS_EXT_STATUS_SHIFT             0x8
#define MAC_1G_STATUS_EXT_STATUS_MASK              0x100UL
#define MAC_1G_STATUS_LINK_100BASE_T2_HALF_DUPLEX_SHIFT 0x9
#define MAC_1G_STATUS_LINK_100BASE_T2_HALF_DUPLEX_MASK 0x600UL
#define MAC_1G_STATUS_LINK_10M_HALF_DUPLEX_SHIFT   0xb
#define MAC_1G_STATUS_LINK_10M_HALF_DUPLEX_MASK    0x1800UL
#define MAC_1G_STATUS_LINK_100BASE_X_HALF_DUPLEX_SHIFT 0xd
#define MAC_1G_STATUS_LINK_100BASE_X_HALF_DUPLEX_MASK 0x6000UL
#define MAC_1G_STATUS_LINK_100BASE_T4_SHIFT        0xf
#define MAC_1G_STATUS_LINK_100BASE_T4_MASK         0x8000UL
#define MAC_1G_STATUS_LINK_STATUS_SHIFT            0x2
#define MAC_1G_STATUS_LINK_STATUS_MASK             0x4UL

/* MAC_SERDES */
#define MAC_SERDES_CTRL_1G_OFFSET                  0x615C
#define MAC_SERDES_CTRL_10G_OFFSET                 0x616C
#define MAC_SERDES_CTRL_25G_OFFSET                 0x617C

/* EMAC */
#define EMAC_CMD_CFG_OFFSET                        0x108
#define EMAC_CMD_CFG_TX_EN_SHIFT                   0x0
#define EMAC_CMD_CFG_TX_EN_MASK                    0x1UL
#define EMAC_CMD_CFG_RX_EN_SHIFT                   0x1
#define EMAC_CMD_CFG_RX_EN_MASK                    0x2UL
#define EMAC_CMD_CFG_PROMIS_EN_SHIFT               0x4
#define EMAC_CMD_CFG_PROMIS_EN_MASK                0x10UL
#define EMAC_CMD_CFG_SW_RESET_SHIFT                0xc
#define EMAC_CMD_CFG_SW_RESET_MASK                 0x1000UL
#define EMAC_CMD_CFG_CNTL_FRAME_EN_SHIFT           0xd
#define EMAC_CMD_CFG_CNTL_FRAME_EN_MASK            0x2000UL
#define EMAC_CMD_CFG_PAUSE_MASK_P_SHIFT            0x11
#define EMAC_CMD_CFG_PAUSE_MASK_P_MASK             0x20000UL
#define EMAC_CMD_CFG_PAUSE_MASK_E_SHIFT            0x12
#define EMAC_CMD_CFG_PAUSE_MASK_E_MASK             0x40000UL
#define EMAC_CMD_CFG_PFC_MODE_SHIFT                0x13
#define EMAC_CMD_CFG_PFC_MODE_MASK                 0x80000UL
#define EMAC_CMD_CFG_PAUSE_PFC_COMP_SHIFT          0x14
#define EMAC_CMD_CFG_PAUSE_PFC_COMP_MASK           0x100000UL
#define EMAC_CMD_CFG_TX_FLUSH_SHIFT                0x16
#define EMAC_CMD_CFG_TX_FLUSH_MASK                 0x400000UL
#define EMAC_CMD_CFG_TX_FIFO_RESET_SHIFT           0x1a
#define EMAC_CMD_CFG_TX_FIFO_RESET_MASK            0x4000000UL
#define EMAC_CMD_CFG_TX_PAUSE_DIS_SHIFT            0x1c
#define EMAC_CMD_CFG_TX_PAUSE_DIS_MASK             0x10000000UL
#define EMAC_CMD_CFG_RX_PAUSE_DIS_SHIFT            0x1d
#define EMAC_CMD_CFG_RX_PAUSE_DIS_MASK             0x20000000UL
#define EMAC_CMD_CFG_PAUSE_FWD_SHIFT               0x7
#define EMAC_CMD_CFG_PAUSE_FWD_MASK                0x80UL
#define EMAC_CMD_CFG_PAUSE_IGNORE_SHIFT            0x8
#define EMAC_CMD_CFG_PAUSE_IGNORE_MASK             0x100UL
#define EMAC_MAC_ADDR_0_OFFSET                     0x10C
#define EMAC_MAC_ADDR_1_OFFSET                     0x110
#define EMAC_FRM_LEN_OFFSET                        0x114
#define EMAC_RX_FIFO_SECTIONS_OFFSET               0x11C
#define EMAC_RX_FIFO_SECTION_FULL_SHIFT            0x0
#define EMAC_RX_FIFO_SECTION_FULL_MASK             0x1FUL
#define EMAC_TX_FIFO_SECTIONS_OFFSET               0x120
#define EMAC_TX_FIFO_SECTION_FULL_SHIFT            0x0
#define EMAC_TX_FIFO_SECTION_FULL_MASK             0x1FUL

/* PMAC */
#define PMAC_CMD_CFG_OFFSET                        0x8
#define PMAC_STATUS_OFFSET                         0x40
#define PMAC_CMD_CFG_TX_EN_SHIFT                   0x0
#define PMAC_CMD_CFG_TX_EN_MASK                    0x1UL
#define PMAC_CMD_CFG_RX_EN_SHIFT                   0x1
#define PMAC_CMD_CFG_RX_EN_MASK                    0x2UL
#define PMAC_CMD_CFG_PROMIS_EN_SHIFT               0x4
#define PMAC_CMD_CFG_PROMIS_EN_MASK                0x10UL
#define PMAC_CMD_CFG_CRC_FWD_SHIFT                 0x6
#define PMAC_CMD_CFG_CRC_FWD_MASK                  0x40UL
#define PMAC_CMD_CFG_LOOPBACK_EN_SHIFT             0xa
#define PMAC_CMD_CFG_LOOPBACK_EN_MASK              0x400UL
#define PMAC_CMD_CFG_TX_PAD_EN_SHIFT               0xb
#define PMAC_CMD_CFG_TX_PAD_EN_MASK                0x800UL
#define PMAC_CMD_CFG_SW_RESET_SHIFT                0xc
#define PMAC_CMD_CFG_SW_RESET_MASK                 0x1000UL
#define PMAC_CMD_CFG_CNTL_FRAME_EN_SHIFT           0xd
#define PMAC_CMD_CFG_CNTL_FRAME_EN_MASK            0x2000UL
#define PMAC_CMD_CFG_PHY_TX_EN_SHIFT               0xf
#define PMAC_CMD_CFG_PHY_TX_EN_MASK                0x8000UL
#define PMAC_CMD_CFG_PFC_MODE_SHIFT                0x13
#define PMAC_CMD_CFG_PFC_MODE_MASK                 0x80000UL
#define PMAC_CMD_CFG_PAUSE_IGNORE_SHIFT            0x8
#define PMAC_CMD_CFG_PAUSE_IGNORE_MASK             0x100UL
#define PMAC_CMD_CFG_PAUSE_FWD_SHIFT               0x7
#define PMAC_CMD_CFG_PAUSE_FWD_MASK                0x80UL
#define PMAC_FRM_LEN_OFFSET                        0x14
#define PMAC_MAC_ADDR_0_OFFSET                     0xC
#define PMAC_MAC_ADDR_1_OFFSET                     0x10
#define PMAC_RX_FIFO_SECTIONS_OFFSET               0x1C
#define PMAC_RX_FIFO_SECTION_FULL_SHIFT            0x0
#define PMAC_RX_FIFO_SECTION_FULL_MASK             0x1FUL
#define PMAC_TX_FIFO_SECTIONS_OFFSET               0x20
#define PMAC_TX_FIFO_SECTION_FULL_SHIFT            0x0
#define PMAC_TX_FIFO_SECTION_FULL_MASK             0x1FUL
#define PMAC_MDIO_CFG_STATUS_OFFSET                0x30
#define PMAC_STATUS_OFFSET                         0x40
#define PMAC_STATUS_RX_LOC_FAULT_SHIFT             0x0
#define PMAC_STATUS_RX_LOC_FAULT_MASK              0x1UL
#define PMAC_STATUS_RX_REM_FAULT_SHIFT             0x1
#define PMAC_STATUS_RX_REM_FAULT_MASK              0x2UL
#define PMAC_STATUS_PHY_LOS_SHIFT                  0x2
#define PMAC_STATUS_PHY_LOS_MASK                   0x4UL
#define PMAC_STATUS_TS_AVAIL_SHIFT                 0x3
#define PMAC_STATUS_TS_AVAIL_MASK                  0x8UL
#define PMAC_STATUS_RX_LOWP_SHIFT                  0x4
#define PMAC_STATUS_RX_LOWP_MASK                   0x10UL
#define PMAC_STATUS_PMAC_TX_EMPTY_SHIFT            0x5
#define PMAC_STATUS_PMAC_TX_EMPTY_MASK             0x20UL
#define PMAC_STATUS_PMAC_RX_EMPTY_SHIFT            0x6
#define PMAC_STATUS_PMAC_RX_EMPTY_MASK             0x40UL
#define PMAC_STATUS_RX_LINT_FAULT_SHIFT            0x7
#define PMAC_STATUS_RX_LINT_FAULT_MASK             0x80UL
#define PMAC_STATUS_RX_LINT_FAULT_SHIFT            0x7
#define PMAC_STATUS_RX_LINT_FAULT_MASK             0x80UL
#define PMAC_STATUS_TX_MERGE_ISIDLE_SHIFT          0x9
#define PMAC_STATUS_TX_MERGE_ISIDLE_MASK           0x200UL
#define PMAC_STATUS_EMAC_TX_EMPTY_SHIFT            0x15
#define PMAC_STATUS_EMAC_TX_EMPTY_MASK             0x200000UL
#define PMAC_STATUS_EMAC_RX_EMPTY_SHIFT            0x16
#define PMAC_STATUS_EMAC_RX_EMPTY_MASK             0x400000UL
#define PMAC_XIF_OFFSET                            0x80
#define PMAC_XIF_XGMII_EN_SHIFT                    0x0
#define PMAC_XIF_XGMII_EN_MASK                     0x1UL
#define PMAC_XIF_PAUSETIMERX8_SHIFT                0x4
#define PMAC_XIF_PAUSETIMERX8_MASK                 0x10UL
#define PMAC_XIF_ONE_STEP_EN_SHIFT                 0x5
#define PMAC_XIF_ONE_STEP_EN_MASK                  0x20UL
#define PMAC_XIF_EMAC_RX_PAUSE_BYPASS_SHIFT        0x6
#define PMAC_XIF_EMAC_RX_PAUSE_BYPASS_MASK         0x40UL
#define PMAC_XIF_PMAC_RX_PAUSE_BYPASS_SHIFT        0x7
#define PMAC_XIF_PMAC_RX_PAUSE_BYPASS_MASK         0x80UL
#define PMAC_XIF_TX_MAC_RS_ERR_SHIFT               0x8
#define PMAC_XIF_TX_MAC_RS_ERR_MASK                0x100UL
#define PMAC_XIF_TS_DELTA_MODE_SHIFT               0x9
#define PMAC_XIF_TS_DELTA_MODE_MASK                0x200UL
#define PMAC_XIF_TS_DELAY_MODE_SHIFT               0xa
#define PMAC_XIF_TS_DELAY_MODE_MASK                0x400UL
#define PMAC_XIF_TS_BINARY_MODE_SHIFT              0xb
#define PMAC_XIF_TS_BINARY_MODE_MASK               0x800UL
#define PMAC_XIF_TS_UPD64_MODE_SHIFT               0xc
#define PMAC_XIF_TS_UPD64_MODE_MASK                0x1000UL
#define PMAC_TX_IPG_LEN_OFFSET                     0x44
#define PMAC_TX_IPG_LEN_TXIPG_DIC_DISABLE_SHIFT    0x0
#define PMAC_TX_IPG_LEN_TXIPG_DIC_DISABLE_MASK     0x1UL
#define PMAC_TX_IPG_LEN_TXIPG_SHIFT                0x2
#define PMAC_TX_IPG_LEN_TXIPG_MASK                 0x3CUL
#define PMAC_TX_IPG_LEN_COMPENSATION_SHIFT         0x10
#define PMAC_TX_IPG_LEN_COMPENSATION_MASK          0xFFFF0000UL

/* XPCS */
#define XPCS_OFFSET                                0x4000
#define XPCS_ELEM_SIZE                             0x800
#define XPCS_CTRL1_OFFSET                          0x0
#define XPCS_CTRL1_SPEED_SELECTION_SHIFT           0x2
#define XPCS_CTRL1_SPEED_SELECTION_MASK            0x3CUL
#define XPCS_CTRL1_SPEED_ALWAYS1_SHIFT             0x6
#define XPCS_CTRL1_SPEED_ALWAYS1_MASK              0x40UL
#define XPCS_CTRL1_LOW_POWER_SHIFT                 0xb
#define XPCS_CTRL1_LOW_POWER_MASK                  0x800UL
#define XPCS_CTRL1_SPEED_SELECT_ALWAYS1_SHIFT      0xd
#define XPCS_CTRL1_SPEED_SELECT_ALWAYS1_MASK       0x2000UL
#define XPCS_CTRL1_LOOPBACK_SHIFT                  0xe
#define XPCS_CTRL1_LOOPBACK_MASK                   0x4000UL
#define XPCS_CTRL1_RESET_SHIFT                     0xf
#define XPCS_CTRL1_RESET_MASK                      0x8000UL
#define XPCS_CTRL2_OFFSET                          0x1C
#define XPCS_CTRL2_PCS_TYPE_SHIFT                  0x0
#define XPCS_CTRL2_PCS_TYPE_MASK                   0x7UL
#define XPCS_STATUS1_OFFSET                        0x4
#define XPCS_STATUS2_OFFSET                        0x20
#define XPCS_SPEED_ABILITY_OFFSET                  0x10
#define XPCS_VENDOR_VL0_0_OFFSET                   0x720
#define XPCS_VENDOR_PCS_MODE_OFFSET                0x740
#define XPCS_VENDOR_PCS_MODE_ENA_CLAUSE49_SHIFT    0x0
#define XPCS_VENDOR_PCS_MODE_ENA_CLAUSE49_MASK     0x1UL
#define XPCS_VENDOR_PCS_MODE_DISABLE_MLD_SHIFT     0x1
#define XPCS_VENDOR_PCS_MODE_DISABLE_MLD_MASK      0x2UL
#define XPCS_VENDOR_PCS_MODE_HI_BER25_SHIFT        0x2
#define XPCS_VENDOR_PCS_MODE_HI_BER25_MASK         0x4UL
#define XPCS_VENDOR_PCS_MODE_UNDESC_SHIFT          0x3
#define XPCS_VENDOR_PCS_MODE_UNDESC_MASK           0x8UL
#define XPCS_VENDOR_PCS_MODE_ST_ENA_CLAUSE49_SHIFT 0x8
#define XPCS_VENDOR_PCS_MODE_ST_ENA_CLAUSE49_MASK  0x100UL
#define XPCS_VENDOR_PCS_MODE_ST_DISABLE_MLD_SHIFT  0x9
#define XPCS_VENDOR_PCS_MODE_ST_DISABLE_MLD_MASK   0x200UL
#define XPCS_VENDOR_VL_INTVL_OFFSET                0x708
#define XPCS_VENDOR_VL_INTVL_MARKER_COUNTER_SHIFT  0x0
#define XPCS_VENDOR_VL_INTVL_MARKER_COUNTER_MASK   0xFFFFUL
#define XPCS_VENDOR_TXLANE_THRESH_OFFSET           0x70C
#define XPCS_VENDOR_TXLANE_THRESH_THRESHOLD_SHIFT  0x0
#define XPCS_VENDOR_TXLANE_THRESH_THRESHOLD_MASK   0xFUL

/* PCS_100G */
#define PCS_100G_OFFSET                            0x7000
#define PCS_100G_ELEM_SIZE                         0xA00
#define PCS_100G_CTRL1_OFFSET                      0x0
#define PCS_100G_CTRL1_SPEED_SEL_SHIFT             0x2
#define PCS_100G_CTRL1_SPEED_SEL_MASK              0x3CUL
#define PCS_100G_CTRL1_SPEED_SEL6_SHIFT            0x6
#define PCS_100G_CTRL1_SPEED_SEL6_MASK             0x40UL
#define PCS_100G_CTRL1_LOW_POWER_SHIFT             0xb
#define PCS_100G_CTRL1_LOW_POWER_MASK              0x800UL
#define PCS_100G_CTRL1_SPEED_SEL13_SHIFT           0xd
#define PCS_100G_CTRL1_SPEED_SEL13_MASK            0x2000UL
#define PCS_100G_CTRL1_LOOPBACK_SHIFT              0xe
#define PCS_100G_CTRL1_LOOPBACK_MASK               0x4000UL
#define PCS_100G_CTRL1_RESET_SHIFT                 0xf
#define PCS_100G_CTRL1_RESET_MASK                  0x8000UL
#define PCS_100G_CTRL2_OFFSET                      0x1C
#define PCS_100G_CTRL2_PCS_TYPE_SHIFT              0x0
#define PCS_100G_CTRL2_PCS_TYPE_MASK               0x7UL
#define PCS_100G_STATUS1_OFFSET                    0x4
#define PCS_100G_STATUS1_LOW_POWER_ABILITY_SHIFT   0x1
#define PCS_100G_STATUS1_LOW_POWER_ABILITY_MASK    0x2UL
#define PCS_100G_STATUS1_PCS_RECEIVE_LINK_SHIFT    0x2
#define PCS_100G_STATUS1_PCS_RECEIVE_LINK_MASK     0x4UL
#define PCS_100G_STATUS1_FAULT_SHIFT               0x7
#define PCS_100G_STATUS1_FAULT_MASK                0x80UL
#define PCS_100G_STATUS2_OFFSET                    0x20
#define PCS_100G_STATUS2_RECEIVE_FAULT_SHIFT       0xa
#define PCS_100G_STATUS2_RECEIVE_FAULT_MASK        0x400UL
#define PCS_100G_STATUS2_TRANSMIT_FAULT_SHIFT      0xb
#define PCS_100G_STATUS2_TRANSMIT_FAULT_MASK       0x800UL
#define PCS_100G_STATUS2_DEVICE_PRESENT_SHIFT      0xe
#define PCS_100G_STATUS2_DEVICE_PRESENT_MASK       0xC000UL
#define PCS_100G_SPEED_ABILITY_OFFSET              0x10
#define PCS_100G_BASER_STATUS1_OFFSET              0x80
#define PCS_100G_BASER_STATUS1_BLOCK_LOCK_SHIFT    0x0
#define PCS_100G_BASER_STATUS1_BLOCK_LOCK_MASK     0x1UL
#define PCS_100G_BASER_STATUS1_HIGH_BER_SHIFT      0x1
#define PCS_100G_BASER_STATUS1_HIGH_BER_MASK       0x2UL
#define PCS_100G_BASER_STATUS1_RECEIVE_LINK_SHIFT  0xc
#define PCS_100G_BASER_STATUS1_RECEIVE_LINK_MASK   0x1000UL
#define PCS_100G_VL_INTVL_OFFSET                   0x808
#define PCS_100G_VL_INTVL_SHIFT                    0x0
#define PCS_100G_VL_INTVL_MASK                     0xFFFFUL

/* MAC_AN */
#define MAC_CTRL_AN_OFFSET                         0x0
#define MAC_CTRL_AN_ELEM_SIZE                      0x400
#define MAC_CTRL_AN_CTRL_OFFSET                    0x6008
#define MAC_CTRL_AN_CTRL_EN_SHIFT                  0x0
#define MAC_CTRL_AN_CTRL_EN_MASK                   0xFUL
#define MAC_CTRL_AN_CTRL_DIS_TIMER_SHIFT           0x4
#define MAC_CTRL_AN_CTRL_DIS_TIMER_MASK            0xF0UL
#define MAC_CTRL_AN_CTRL_PCS_LINK_STATUS_SHIFT     0x8
#define MAC_CTRL_AN_CTRL_PCS_LINK_STATUS_MASK      0xF00UL
#define MAC_CTRL_AN_STATUS_OFFSET                  0x6010
#define MAC_CTRL_AN_STATUS_AN_INT_SHIFT            0x0
#define MAC_CTRL_AN_STATUS_AN_INT_MASK             0x1UL
#define MAC_CTRL_AN_STATUS_AN_DONE_SHIFT           0x1
#define MAC_CTRL_AN_STATUS_AN_DONE_MASK            0x2UL
#define MAC_CTRL_AN_STATUS_AN_VAL_SHIFT            0x2
#define MAC_CTRL_AN_STATUS_AN_VAL_MASK             0x4UL
#define MAC_CTRL_AN_STATUS_AN_STATUS_SHIFT         0x3
#define MAC_CTRL_AN_STATUS_AN_STATUS_MASK          0x8UL
#define MAC_CTRL_AN_STATUS_AN_SELECT_SHIFT         0x4
#define MAC_CTRL_AN_STATUS_AN_SELECT_MASK          0x1F0UL
#define MAC_CTRL_AN_STATUS_AN_TR_DIS_SHIFT         0x9
#define MAC_CTRL_AN_STATUS_AN_TR_DIS_MASK          0x200UL
#define MAC_CTRL_AN_STATUS_AN_FEC_EN_SHIFT         0xa
#define MAC_CTRL_AN_STATUS_AN_FEC_EN_MASK          0x400UL
#define MAC_CTRL_AN_STATUS_AN_RS_FEC_EN_SHIFT      0xb
#define MAC_CTRL_AN_STATUS_AN_RS_FEC_EN_MASK       0x800UL
#define MAC_CTRL_AN_STATUS_AN_STATE_SHIFT          0xc
#define MAC_CTRL_AN_STATUS_AN_STATE_MASK           0xF000UL
#define MAC_CTRL_AN_STATUS_LT_INT_SHIFT            0x10
#define MAC_CTRL_AN_STATUS_LT_INT_MASK             0x10000UL
#define MAC_CTRL_AN_STATUS_LT_VAL_SHIFT            0x11
#define MAC_CTRL_AN_STATUS_LT_VAL_MASK             0x20000UL
#define MAC_CTRL_AN_STATUS_LT_STATUS_SHIFT         0x12
#define MAC_CTRL_AN_STATUS_LT_STATUS_MASK          0x40000UL
#define MAC_CTRL_AN_STATUS_LT_LOCK_SHIFT           0x13
#define MAC_CTRL_AN_STATUS_LT_LOCK_MASK            0x80000UL
#define MAC_CTRL_AN_AN_XNP_0_OFFSET                0x24
#define MAC_CTRL_AN_AN_XNP_0_NEXTPAGE_SHIFT        0x0
#define MAC_CTRL_AN_AN_XNP_0_NEXTPAGE_MASK         0xFFFFUL
#define MAC_CTRL_AN_AN_XNP_1_OFFSET                0x28
#define MAC_CTRL_AN_AN_XNP_1_NEXTPAGE_SHIFT        0x0
#define MAC_CTRL_AN_AN_XNP_1_NEXTPAGE_MASK         0xFFFFUL
#define MAC_CTRL_AN_AN_XNP_2_OFFSET                0x2C
#define MAC_CTRL_AN_AN_XNP_2_NEXTPAGE_SHIFT        0x0
#define MAC_CTRL_AN_AN_XNP_2_NEXTPAGE_MASK         0xFFFFUL
#define MAC_CTRL_AN_LP_AN_XNP_0_OFFSET             0x30
#define MAC_CTRL_AN_LP_AN_XNP_0_REMNEXTPAGE_SHIFT  0x0
#define MAC_CTRL_AN_LP_AN_XNP_0_REMNEXTPAGE_MASK   0xFFFFUL
#define MAC_CTRL_AN_LP_AN_XNP_1_OFFSET             0x34
#define MAC_CTRL_AN_LP_AN_XNP_1_REMNEXTPAGE_SHIFT  0x0
#define MAC_CTRL_AN_LP_AN_XNP_1_REMNEXTPAGE_MASK   0xFFFFUL
#define MAC_CTRL_AN_LP_AN_XNP_2_OFFSET             0x38
#define MAC_CTRL_AN_LP_AN_XNP_2_REMNEXTPAGE_SHIFT  0x0
#define MAC_CTRL_AN_LP_AN_XNP_2_REMNEXTPAGE_MASK   0xFFFFUL

/* LINKTRAINING */
#define LT_OFFSET                                  0x1000
#define LT_ELEM_SIZE                               0x400
#define LT_KR_CTRL_OFFSET                          0x0
#define LT_KR_CTRL_RESTARTTRAINING_SHIFT           0x0
#define LT_KR_CTRL_RESTARTTRAINING_MASK            0x1UL
#define LT_KR_CTRL_TRAININGEN_SHIFT                0x1
#define LT_KR_CTRL_TRAININGEN_MASK                 0x2UL
#define LT_KR_STATUS_OFFSET                        0x4
#define LT_KR_STATUS_RECEIVERSTATUS_SHIFT          0x0
#define LT_KR_STATUS_RECEIVERSTATUS_MASK           0x1UL
#define LT_KR_STATUS_FRAMELOCK_SHIFT               0x1
#define LT_KR_STATUS_FRAMELOCK_MASK                0x2UL
#define LT_KR_STATUS_STATUS_SHIFT                  0x2
#define LT_KR_STATUS_STATUS_MASK                   0x4UL
#define LT_KR_STATUS_TRAININGFAIL_SHIFT            0x3
#define LT_KR_STATUS_TRAININGFAIL_MASK             0x8UL
#define LT_KR_STATUS_SIGNALDETECTION_SHIFT         0xf
#define LT_KR_STATUS_SIGNALDETECTION_MASK          0x8000UL
#define LT_KR_MAX_WAIT_TIMER_OFFSET                0x38
#define LT_KR_MAX_WAIT_TIMER_SHIFT                 0x0
#define LT_KR_MAX_WAIT_TIMER_MASK                  0xFFFFUL
#define LT_KR_MODE_OFFSET                          0x3C
#define LT_KR_MODE_MAX_WAIT_TIMER_DIS_SHIFT        0x0
#define LT_KR_MODE_MAX_WAIT_TIMER_DIS_MASK         0x1UL
#define LT_KR_MODE_MAX_WAIT_TIMER_OVR_EAN_SHIFT    0x1
#define LT_KR_MODE_MAX_WAIT_TIMER_OVR_EAN_MASK     0x2UL

/* AN_KXAN */
#define AN_KXAN_CTRL_OFFSET                        0x0
#define AN_KXAN_CTRL_INCOMP_LINKDISABLE_SHIFT      0x0
#define AN_KXAN_CTRL_INCOMP_LINKDISABLE_MASK       0x1UL
#define AN_KXAN_CTRL_ANRESTART_SHIFT               0x9
#define AN_KXAN_CTRL_ANRESTART_MASK                0x200UL
#define AN_KXAN_CTRL_ANEN_SHIFT                    0xc
#define AN_KXAN_CTRL_ANEN_MASK                     0x1000UL
#define AN_KXAN_CTRL_NEXTPAGEEN_SHIFT              0xd
#define AN_KXAN_CTRL_NEXTPAGEEN_MASK               0x2000UL
#define AN_KXAN_CTRL_RESET_SHIFT                   0xf
#define AN_KXAN_CTRL_RESET_MASK                    0x8000UL
#define AN_KXAN_STATUS_OFFSET                      0x4
#define AN_KXAN_STATUS_LPANCAPABLE_SHIFT           0x0
#define AN_KXAN_STATUS_LPANCAPABLE_MASK            0x1UL
#define AN_KXAN_STATUS_LINKSTATUS_SHIFT            0x2
#define AN_KXAN_STATUS_LINKSTATUS_MASK             0x4UL
#define AN_KXAN_STATUS_AN_ABILITY_SHIFT            0x3
#define AN_KXAN_STATUS_AN_ABILITY_MASK             0x8UL
#define AN_KXAN_STATUS_REMOTEFAULT_SHIFT           0x4
#define AN_KXAN_STATUS_REMOTEFAULT_MASK            0x10UL
#define AN_KXAN_STATUS_AN_COMPLETE_SHIFT           0x5
#define AN_KXAN_STATUS_AN_COMPLETE_MASK            0x20UL
#define AN_KXAN_STATUS_PAGERECEIVED_SHIFT          0x6
#define AN_KXAN_STATUS_PAGERECEIVED_MASK           0x40UL
#define AN_KXAN_STATUS_EXTDNEXTPAGE_SHIFT          0x7
#define AN_KXAN_STATUS_EXTDNEXTPAGE_MASK           0x80UL
#define AN_KXAN_STATUS_PARALLELDETECTFAULT_SHIFT   0x9
#define AN_KXAN_STATUS_PARALLELDETECTFAULT_MASK    0x200UL
#define AN_KXAN_ABILITY_0_OFFSET                   0x8
#define AN_KXAN_ABILITY_0_SEL_SHIFT                0x0
#define AN_KXAN_ABILITY_0_SEL_MASK                 0x1FUL
#define AN_KXAN_ABILITY_0_ECHOEDNONCE_SHIFT        0x5
#define AN_KXAN_ABILITY_0_ECHOEDNONCE_MASK         0x3E0UL
#define AN_KXAN_ABILITY_0_PAUSEABILITY_SHIFT       0xa
#define AN_KXAN_ABILITY_0_PAUSEABILITY_MASK        0x1C00UL
#define AN_KXAN_ABILITY_0_REMOTEFAULT_SHIFT        0xd
#define AN_KXAN_ABILITY_0_REMOTEFAULT_MASK         0x2000UL
#define AN_KXAN_ABILITY_0_ACK_SHIFT                0xe
#define AN_KXAN_ABILITY_0_ACK_MASK                 0x4000UL
#define AN_KXAN_ABILITY_0_NEXTPAGE_SHIFT           0xf
#define AN_KXAN_ABILITY_0_NEXTPAGE_MASK            0x8000UL
#define AN_KXAN_ABILITY_1_OFFSET                   0xC
#define AN_KXAN_ABILITY_1_TXNONCE_SHIFT            0x0
#define AN_KXAN_ABILITY_1_TXNONCE_MASK             0x1FUL
#define AN_KXAN_ABILITY_1_TECHNOLOGY_SHIFT         0x5
#define AN_KXAN_ABILITY_1_TECHNOLOGY_MASK          0xFFE0UL
#define AN_KXAN_ABILITY_2_OFFSET                   0x10
#define AN_KXAN_ABILITY_2_TECHNOLOGY_SHIFT         0x0
#define AN_KXAN_ABILITY_2_TECHNOLOGY_MASK          0x3FFFUL
#define AN_KXAN_ABILITY_2_FECABILITY_SHIFT         0xe
#define AN_KXAN_ABILITY_2_FECABILITY_MASK          0xC000UL
#define AN_KXAN_MS_COUNT_OFFSET                    0x20
#define AN_KXAN_MS_COUNT_NUMCLOCKS_SHIFT           0x0
#define AN_KXAN_MS_COUNT_NUMCLOCKS_MASK            0xFFFFUL

/* AN_BP */
#define AN_BP_STATUS_OFFSET                        0x3C
#define AN_BP_STATUS_PRESENT_SHIFT                 0x0
#define AN_BP_STATUS_PRESENT_MASK                  0x1UL
#define AN_BP_STATUS_TECHNOLOGY_A0_SHIFT           0x1
#define AN_BP_STATUS_TECHNOLOGY_A0_MASK            0x2UL
#define AN_BP_STATUS_TECHNOLOGY_A1_SHIFT           0x2
#define AN_BP_STATUS_TECHNOLOGY_A1_MASK            0x4UL
#define AN_BP_STATUS_TECHNOLOGY_A2_SHIFT           0x3
#define AN_BP_STATUS_TECHNOLOGY_A2_MASK            0x8UL
#define AN_BP_STATUS_FEC_SHIFT                     0x4
#define AN_BP_STATUS_FEC_MASK                      0x10UL
#define AN_BP_STATUS_TECHNOLOGY_A3_SHIFT           0x5
#define AN_BP_STATUS_TECHNOLOGY_A3_MASK            0x20UL
#define AN_BP_STATUS_TECHNOLOGY_A4_SHIFT           0x6
#define AN_BP_STATUS_TECHNOLOGY_A4_MASK            0x40UL
#define AN_BP_STATUS_BPETHSTATUSRSV_SHIFT          0x7
#define AN_BP_STATUS_BPETHSTATUSRSV_MASK           0x80UL
#define AN_BP_STATUS_TECHNOLOGY_A5_SHIFT           0x8
#define AN_BP_STATUS_TECHNOLOGY_A5_MASK            0x100UL
#define AN_BP_STATUS_TECHNOLOGY_A6_SHIFT           0x9
#define AN_BP_STATUS_TECHNOLOGY_A6_MASK            0x200UL
#define AN_BP_STATUS_TECHNOLOGY_A7_SHIFT           0xa
#define AN_BP_STATUS_TECHNOLOGY_A7_MASK            0x400UL
#define AN_BP_STATUS_TECHNOLOGY_A8_SHIFT           0xb
#define AN_BP_STATUS_TECHNOLOGY_A8_MASK            0x800UL
#define AN_BP_STATUS_TECHNOLOGY_A9_SHIFT           0xc
#define AN_BP_STATUS_TECHNOLOGY_A9_MASK            0x1000UL
#define AN_BP_STATUS_TECHNOLOGY_A10_SHIFT          0xd
#define AN_BP_STATUS_TECHNOLOGY_A10_MASK           0x2000UL
#define AN_BP_STATUS_TECHNOLOGY_A11_SHIFT          0xe
#define AN_BP_STATUS_TECHNOLOGY_A11_MASK           0x4000UL
#define AN_BP_STATUS_TECHNOLOGY_A12_SHIFT          0xf
#define AN_BP_STATUS_TECHNOLOGY_A12_MASK           0x8000UL
#define AN_BP_STATUS_2_OFFSET                      0x40
#define AN_BP_STATUS_2_TECHNOLOGY_A13_SHIFT        0x0
#define AN_BP_STATUS_2_TECHNOLOGY_A13_MASK         0x1UL
#define AN_BP_STATUS_2_TECHNOLOGY_A14_SHIFT        0x1
#define AN_BP_STATUS_2_TECHNOLOGY_A14_MASK         0x2UL
#define AN_BP_STATUS_2_TECHNOLOGY_A15_SHIFT        0x2
#define AN_BP_STATUS_2_TECHNOLOGY_A15_MASK         0x4UL

/* MAC_PLL_10G */
#define MAC_PLL_10G_OFFSET                         0x6110
#define MAC_PLL_10G_REF_CLK_MPLL_DIV_SHIFT         0x0
#define MAC_PLL_10G_REF_CLK_MPLL_DIV_MASK          0x7UL
#define MAC_PLL_10G_FB_CLK_DIV4_EN_SHIFT           0x3
#define MAC_PLL_10G_FB_CLK_DIV4_EN_MASK            0x8UL
#define MAC_PLL_10G_MULTIPLIER_SHIFT               0x4
#define MAC_PLL_10G_MULTIPLIER_MASK                0xFFF0UL
#define MAC_PLL_10G_DIV16P5_CLK_EN_SHIFT           0x10
#define MAC_PLL_10G_DIV16P5_CLK_EN_MASK            0x10000UL
#define MAC_PLL_10G_DIV_CLK_EN_SHIFT               0x11
#define MAC_PLL_10G_DIV_CLK_EN_MASK                0x20000UL
#define MAC_PLL_10G_DIV_MULTIPLIER_SHIFT           0x12
#define MAC_PLL_10G_DIV_MULTIPLIER_MASK            0x3FC0000UL
#define MAC_PLL_10G_TX_CLK_DIV_SHIFT               0x1a
#define MAC_PLL_10G_TX_CLK_DIV_MASK                0x1C000000UL
#define MAC_PLL_10G_WORD_CLK_DIV_SHIFT             0x1d
#define MAC_PLL_10G_WORD_CLK_DIV_MASK              0x60000000UL
#define MAC_PLL_10G_INIT_CAL_DIS_SHIFT             0x1f
#define MAC_PLL_10G_INIT_CAL_DIS_MASK              0x80000000UL
#define MAC_PLL_10G_SSC_OFFSET                     0x6118
#define MAC_PLL_10G_SSC_SSC_EN_SHIFT               0x0
#define MAC_PLL_10G_SSC_SSC_EN_MASK                0x1
#define MAC_PLL_10G_SSC_SSC_UP_SPREAD_SHIFT        0x1
#define MAC_PLL_10G_SSC_SSC_UP_SPREAD_MASK         0x2
#define MAC_PLL_10G_SSC_SSC_PEAK_SHIFT             0x2
#define MAC_PLL_10G_SSC_SSC_PEAK_MASK              0x3FFFFC
#define MAC_PLL_10G_SSC_SSC_STEP_SIZE_SHIFT        0x20
#define MAC_PLL_10G_SSC_SSC_STEP_SIZE_MASK         0x1FFFFF00000000
#define MAC_PLL_10G_FRAC_OFFSET                    0x6120
#define MAC_PLL_10G_FRAC_EN_SHIFT                  0x0
#define MAC_PLL_10G_FRAC_EN_MASK                   0x1
#define MAC_PLL_10G_FRAC_QUOT_SHIFT                0x10
#define MAC_PLL_10G_FRAC_QUOT_MASK                 0xFFFF0000
#define MAC_PLL_10G_FRAC_DEN_SHIFT                 0x20
#define MAC_PLL_10G_FRAC_DEN_MASK                  0xFFFF00000000
#define MAC_PLL_10G_FRAC_REM_SHIFT                 0x30
#define MAC_PLL_10G_FRAC_REM_MASK                  0xFFFF000000000000
#define MAC_PLL_10G_BW_OFFSET                      0x6128
#define MAC_PLL_10G_BW_THRESHOLD_SHIFT             0x0
#define MAC_PLL_10G_BW_THRESHOLD_MASK              0x3
#define MAC_PLL_10G_BW_CTL_BUF_BYPASS_SHIFT        0x2
#define MAC_PLL_10G_BW_CTL_BUF_BYPASS_MASK         0x4
#define MAC_PLL_10G_BW_SHORT_LOCK_EN_SHIFT         0x3
#define MAC_PLL_10G_BW_SHORT_LOCK_EN_MASK          0x8
#define MAC_PLL_10G_BW_SERDES_CLK_SEL_SHIFT        0x4
#define MAC_PLL_10G_BW_SERDES_CLK_SEL_MASK         0x70
#define MAC_PLL_10G_BW_CORE_CLK_SEL_SHIFT          0x7
#define MAC_PLL_10G_BW_CORE_CLK_SEL_MASK           0x380
#define MAC_PLL_10G_BW_LOW_SHIFT                   0x20
#define MAC_PLL_10G_BW_LOW_MASK                    0xFFFF00000000
#define MAC_PLL_10G_BW_HIGH_SHIFT                  0x30
#define MAC_PLL_10G_BW_HIGH_MASK                   0xFFFF000000000000

/* SERDES_CDR_10G */
#define MAC_SERDES_CDR_10G_OFFSET                  0x6160
#define MAC_SERDES_CDR_10G_VCO_CFG_SHIFT           0x0
#define MAC_SERDES_CDR_10G_VCO_CFG_MASK            0xFFF
#define MAC_SERDES_CDR_10G_DCC_CTRL_RANGE_SHIFT    0xc
#define MAC_SERDES_CDR_10G_DCC_CTRL_RANGE_MASK     0xF000
#define MAC_SERDES_CDR_10G_SIGDET_LF_THRES_SHIFT   0x10
#define MAC_SERDES_CDR_10G_SIGDET_LF_THRES_MASK    0x70000
#define MAC_SERDES_CDR_10G_SIGDET_HF_THRES_SHIFT   0x13
#define MAC_SERDES_CDR_10G_SIGDET_HF_THRES_MASK    0x380000
#define MAC_SERDES_CDR_10G_SSC_EN_SHIFT            0x16
#define MAC_SERDES_CDR_10G_SSC_EN_MASK             0x400000
#define MAC_SERDES_CDR_10G_SIGDET_HF_EN_SHIFT      0x17
#define MAC_SERDES_CDR_10G_SIGDET_HF_EN_MASK       0x800000
#define MAC_SERDES_CDR_10G_SIGDET_LFPS_FILTER_EN_SHIFT 0x18
#define MAC_SERDES_CDR_10G_SIGDET_LFPS_FILTER_EN_MASK 0x1000000
#define MAC_SERDES_CDR_10G_DFE_BYPASS_SHIFT        0x19
#define MAC_SERDES_CDR_10G_DFE_BYPASS_MASK         0x2000000
#define MAC_SERDES_CDR_10G_TERM_CTRL_SHIFT         0x1a
#define MAC_SERDES_CDR_10G_TERM_CTRL_MASK          0x1C000000
#define MAC_SERDES_CDR_10G_TERM_ACDC_SHIFT         0x1d
#define MAC_SERDES_CDR_10G_TERM_ACDC_MASK          0x20000000
#define MAC_SERDES_CDR_10G_REF_LD_VAL_SHIFT        0x20
#define MAC_SERDES_CDR_10G_REF_LD_VAL_MASK         0x7F00000000
#define MAC_SERDES_CDR_10G_CDR_PPM_MAX_SHIFT       0x27
#define MAC_SERDES_CDR_10G_CDR_PPM_MAX_MASK        0xF8000000000
#define MAC_SERDES_CDR_10G_VCO_LD_VAL_SHIFT        0x2c
#define MAC_SERDES_CDR_10G_VCO_LD_VAL_MASK         0x1FFF00000000000

/* SERDES_EQ_10G */
#define MAC_SERDES_EQ_10G_OFFSET                   0x6168
#define MAC_SERDES_EQ_10G_ATT_LVL_SHIFT            0x0
#define MAC_SERDES_EQ_10G_ATT_LVL_MASK             0x7UL
#define MAC_SERDES_EQ_10G_CTLE_BOOST_SHIFT         0x3
#define MAC_SERDES_EQ_10G_CTLE_BOOST_MASK          0xF8UL
#define MAC_SERDES_EQ_10G_CTLE_POLE_SHIFT          0x8
#define MAC_SERDES_EQ_10G_CTLE_POLE_MASK           0x300UL
#define MAC_SERDES_EQ_10G_AFE_RATE_SHIFT           0xa
#define MAC_SERDES_EQ_10G_AFE_RATE_MASK            0x1C00UL
#define MAC_SERDES_EQ_10G_VGA1_GAIN_SHIFT          0xd
#define MAC_SERDES_EQ_10G_VGA1_GAIN_MASK           0xE000UL
#define MAC_SERDES_EQ_10G_VGA2_GAIN_SHIFT          0x10
#define MAC_SERDES_EQ_10G_VGA2_GAIN_MASK           0x70000UL
#define MAC_SERDES_EQ_10G_DFE_TAP1_SHIFT           0x13
#define MAC_SERDES_EQ_10G_DFE_TAP1_MASK            0x7F80000UL
#define MAC_SERDES_EQ_10G_DELTA_IQ_SHIFT           0x1b
#define MAC_SERDES_EQ_10G_DELTA_IQ_MASK            0x78000000UL

/* SERDES_CTRL_10G */
#define MAC_SERDES_CTRL_10G_OFFSET                 0x616C
#define MAC_SERDES_CTRL_10G_MISC_SHIFT             0x0
#define MAC_SERDES_CTRL_10G_MISC_MASK              0xFFUL
#define MAC_SERDES_CTRL_10G_WIDTH_SHIFT            0x8
#define MAC_SERDES_CTRL_10G_WIDTH_MASK             0x700UL
#define MAC_SERDES_CTRL_10G_TX_RATE_SHIFT          0xb
#define MAC_SERDES_CTRL_10G_TX_RATE_MASK           0x3800UL
#define MAC_SERDES_CTRL_10G_RX_RATE_SHIFT          0xe
#define MAC_SERDES_CTRL_10G_RX_RATE_MASK           0x1C000UL
#define MAC_SERDES_CTRL_10G_DIV16P5_CLK_EN_SHIFT   0x11
#define MAC_SERDES_CTRL_10G_DIV16P5_CLK_EN_MASK    0x20000UL
#define MAC_SERDES_CTRL_10G_ADAPT_SEL_SHIFT        0x12
#define MAC_SERDES_CTRL_10G_ADAPT_SEL_MASK         0x40000UL
#define MAC_SERDES_CTRL_10G_ADAPT_MODE_SHIFT       0x13
#define MAC_SERDES_CTRL_10G_ADAPT_MODE_MASK        0x180000UL
#define MAC_SERDES_CTRL_10G_VBOOST_EN_SHIFT        0x15
#define MAC_SERDES_CTRL_10G_VBOOST_EN_MASK         0x200000UL
#define MAC_SERDES_CTRL_10G_IBOOST_LVL_SHIFT       0x16
#define MAC_SERDES_CTRL_10G_IBOOST_LVL_MASK        0x3C00000UL
#define MAC_SERDES_CTRL_10G_ALIGN_WIDE_XFER_EN_SHIFT 0x1a
#define MAC_SERDES_CTRL_10G_ALIGN_WIDE_XFER_EN_MASK 0x4000000UL

/* MAC_PLL_25G */
#define MAC_PLL_25G_OFFSET                         0x6130
#define MAC_PLL_25G_REF_CLK_MPLL_DIV_SHIFT         0x0
#define MAC_PLL_25G_REF_CLK_MPLL_DIV_MASK          0x7UL
#define MAC_PLL_25G_FB_CLK_DIV4_EN_SHIFT           0x3
#define MAC_PLL_25G_FB_CLK_DIV4_EN_MASK            0x8UL
#define MAC_PLL_25G_MULTIPLIER_SHIFT               0x4
#define MAC_PLL_25G_MULTIPLIER_MASK                0xFFF0UL
#define MAC_PLL_25G_DIV16P5_CLK_EN_SHIFT           0x10
#define MAC_PLL_25G_DIV16P5_CLK_EN_MASK            0x10000UL
#define MAC_PLL_25G_DIV_CLK_EN_SHIFT               0x11
#define MAC_PLL_25G_DIV_CLK_EN_MASK                0x20000UL
#define MAC_PLL_25G_DIV_MULTIPLIER_SHIFT           0x12
#define MAC_PLL_25G_DIV_MULTIPLIER_MASK            0x3FC0000UL
#define MAC_PLL_25G_TX_CLK_DIV_SHIFT               0x1a
#define MAC_PLL_25G_TX_CLK_DIV_MASK                0x1C000000UL
#define MAC_PLL_25G_WORD_CLK_DIV_SHIFT             0x1d
#define MAC_PLL_25G_WORD_CLK_DIV_MASK              0x60000000UL
#define MAC_PLL_25G_INIT_CAL_DIS_SHIFT             0x1f
#define MAC_PLL_25G_INIT_CAL_DIS_MASK              0x80000000UL
#define MAC_PLL_25G_SSC_OFFSET                     0x6138
#define MAC_PLL_25G_SSC_SSC_EN_SHIFT               0x0
#define MAC_PLL_25G_SSC_SSC_EN_MASK                0x1
#define MAC_PLL_25G_SSC_SSC_UP_SPREAD_SHIFT        0x1
#define MAC_PLL_25G_SSC_SSC_UP_SPREAD_MASK         0x2
#define MAC_PLL_25G_SSC_SSC_PEAK_SHIFT             0x2
#define MAC_PLL_25G_SSC_SSC_PEAK_MASK              0x3FFFFC
#define MAC_PLL_25G_SSC_SSC_STEP_SIZE_SHIFT        0x20
#define MAC_PLL_25G_SSC_SSC_STEP_SIZE_MASK         0x1FFFFF00000000
#define MAC_PLL_25G_FRAC_OFFSET                    0x6140
#define MAC_PLL_25G_FRAC_EN_SHIFT                  0x0
#define MAC_PLL_25G_FRAC_EN_MASK                   0x1
#define MAC_PLL_25G_FRAC_QUOT_SHIFT                0x10
#define MAC_PLL_25G_FRAC_QUOT_MASK                 0xFFFF0000
#define MAC_PLL_25G_FRAC_DEN_SHIFT                 0x20
#define MAC_PLL_25G_FRAC_DEN_MASK                  0xFFFF00000000
#define MAC_PLL_25G_FRAC_REM_SHIFT                 0x30
#define MAC_PLL_25G_FRAC_REM_MASK                  0xFFFF000000000000
#define MAC_PLL_25G_BW_OFFSET                      0x6148
#define MAC_PLL_25G_BW_THRESHOLD_SHIFT             0x0
#define MAC_PLL_25G_BW_THRESHOLD_MASK              0x3
#define MAC_PLL_25G_BW_CTL_BUF_BYPASS_SHIFT        0x2
#define MAC_PLL_25G_BW_CTL_BUF_BYPASS_MASK         0x4
#define MAC_PLL_25G_BW_SHORT_LOCK_EN_SHIFT         0x3
#define MAC_PLL_25G_BW_SHORT_LOCK_EN_MASK          0x8
#define MAC_PLL_25G_BW_SERDES_CLK_SEL_SHIFT        0x4
#define MAC_PLL_25G_BW_SERDES_CLK_SEL_MASK         0x70
#define MAC_PLL_25G_BW_CORE_CLK_SEL_SHIFT          0x7
#define MAC_PLL_25G_BW_CORE_CLK_SEL_MASK           0x380
#define MAC_PLL_25G_BW_LOW_SHIFT                   0x20
#define MAC_PLL_25G_BW_LOW_MASK                    0xFFFF00000000
#define MAC_PLL_25G_BW_HIGH_SHIFT                  0x30
#define MAC_PLL_25G_BW_HIGH_MASK                   0xFFFF000000000000

/* SERDES_CDR_25G */
#define MAC_SERDES_CDR_25G_OFFSET                  0x6170
#define MAC_SERDES_CDR_25G_VCO_CFG_SHIFT           0x0
#define MAC_SERDES_CDR_25G_VCO_CFG_MASK            0xFFF
#define MAC_SERDES_CDR_25G_DCC_CTRL_RANGE_SHIFT    0xc
#define MAC_SERDES_CDR_25G_DCC_CTRL_RANGE_MASK     0xF000
#define MAC_SERDES_CDR_25G_SIGDET_LF_THRES_SHIFT   0x10
#define MAC_SERDES_CDR_25G_SIGDET_LF_THRES_MASK    0x70000
#define MAC_SERDES_CDR_25G_SIGDET_HF_THRES_SHIFT   0x13
#define MAC_SERDES_CDR_25G_SIGDET_HF_THRES_MASK    0x380000
#define MAC_SERDES_CDR_25G_SSC_EN_SHIFT            0x16
#define MAC_SERDES_CDR_25G_SSC_EN_MASK             0x400000
#define MAC_SERDES_CDR_25G_SIGDET_HF_EN_SHIFT      0x17
#define MAC_SERDES_CDR_25G_SIGDET_HF_EN_MASK       0x800000
#define MAC_SERDES_CDR_25G_SIGDET_LFPS_FILTER_EN_SHIFT 0x18
#define MAC_SERDES_CDR_25G_SIGDET_LFPS_FILTER_EN_MASK 0x1000000
#define MAC_SERDES_CDR_25G_DFE_BYPASS_SHIFT        0x19
#define MAC_SERDES_CDR_25G_DFE_BYPASS_MASK         0x2000000
#define MAC_SERDES_CDR_25G_TERM_CTRL_SHIFT         0x1a
#define MAC_SERDES_CDR_25G_TERM_CTRL_MASK          0x1C000000
#define MAC_SERDES_CDR_25G_TERM_ACDC_SHIFT         0x1d
#define MAC_SERDES_CDR_25G_TERM_ACDC_MASK          0x20000000
#define MAC_SERDES_CDR_25G_REF_LD_VAL_SHIFT        0x20
#define MAC_SERDES_CDR_25G_REF_LD_VAL_MASK         0x7F00000000
#define MAC_SERDES_CDR_25G_CDR_PPM_MAX_SHIFT       0x27
#define MAC_SERDES_CDR_25G_CDR_PPM_MAX_MASK        0xF8000000000
#define MAC_SERDES_CDR_25G_VCO_LD_VAL_SHIFT        0x2c
#define MAC_SERDES_CDR_25G_VCO_LD_VAL_MASK         0x1FFF00000000000

/* SERDES_EQ_25G */
#define MAC_SERDES_EQ_25G_OFFSET                   0x6178
#define MAC_SERDES_EQ_25G_ATT_LVL_SHIFT            0x0
#define MAC_SERDES_EQ_25G_ATT_LVL_MASK             0x7UL
#define MAC_SERDES_EQ_25G_CTLE_BOOST_SHIFT         0x3
#define MAC_SERDES_EQ_25G_CTLE_BOOST_MASK          0xF8UL
#define MAC_SERDES_EQ_25G_CTLE_POLE_SHIFT          0x8
#define MAC_SERDES_EQ_25G_CTLE_POLE_MASK           0x300UL
#define MAC_SERDES_EQ_25G_AFE_RATE_SHIFT           0xa
#define MAC_SERDES_EQ_25G_AFE_RATE_MASK            0x1C00UL
#define MAC_SERDES_EQ_25G_VGA1_GAIN_SHIFT          0xd
#define MAC_SERDES_EQ_25G_VGA1_GAIN_MASK           0xE000UL
#define MAC_SERDES_EQ_25G_VGA2_GAIN_SHIFT          0x10
#define MAC_SERDES_EQ_25G_VGA2_GAIN_MASK           0x70000UL
#define MAC_SERDES_EQ_25G_DFE_TAP1_SHIFT           0x13
#define MAC_SERDES_EQ_25G_DFE_TAP1_MASK            0x7F80000UL
#define MAC_SERDES_EQ_25G_DELTA_IQ_SHIFT           0x1b
#define MAC_SERDES_EQ_25G_DELTA_IQ_MASK            0x78000000UL

/* SERDES_CTRL_25G */
#define MAC_SERDES_CTRL_25G_OFFSET                 0x617C
#define MAC_SERDES_CTRL_25G_MISC_SHIFT             0x0
#define MAC_SERDES_CTRL_25G_MISC_MASK              0xFFUL
#define MAC_SERDES_CTRL_25G_WIDTH_SHIFT            0x8
#define MAC_SERDES_CTRL_25G_WIDTH_MASK             0x700UL
#define MAC_SERDES_CTRL_25G_TX_RATE_SHIFT          0xb
#define MAC_SERDES_CTRL_25G_TX_RATE_MASK           0x3800UL
#define MAC_SERDES_CTRL_25G_RX_RATE_SHIFT          0xe
#define MAC_SERDES_CTRL_25G_RX_RATE_MASK           0x1C000UL
#define MAC_SERDES_CTRL_25G_DIV16P5_CLK_EN_SHIFT   0x11
#define MAC_SERDES_CTRL_25G_DIV16P5_CLK_EN_MASK    0x20000UL
#define MAC_SERDES_CTRL_25G_ADAPT_SEL_SHIFT        0x12
#define MAC_SERDES_CTRL_25G_ADAPT_SEL_MASK         0x40000UL
#define MAC_SERDES_CTRL_25G_ADAPT_MODE_SHIFT       0x13
#define MAC_SERDES_CTRL_25G_ADAPT_MODE_MASK        0x180000UL
#define MAC_SERDES_CTRL_25G_VBOOST_EN_SHIFT        0x15
#define MAC_SERDES_CTRL_25G_VBOOST_EN_MASK         0x200000UL
#define MAC_SERDES_CTRL_25G_IBOOST_LVL_SHIFT       0x16
#define MAC_SERDES_CTRL_25G_IBOOST_LVL_MASK        0x3C00000UL
#define MAC_SERDES_CTRL_25G_ALIGN_WIDE_XFER_EN_SHIFT 0x1a
#define MAC_SERDES_CTRL_25G_ALIGN_WIDE_XFER_EN_MASK 0x4000000UL

/* STATS64 */
#define STAT64_OFFSET                              0x8000
#define STAT64_RX_OFFSET                           0x0
#define STAT64_RX_ELEM_SIZE                        0x200
#define STAT64_TX_OFFSET                           0x800
#define STAT64_TX_ELEM_SIZE                        0x200

#endif /* ASM_KVX_MAC_REGS_H */
