/* SPDX-License-Identifier: GPL-2.0 */
/*
 * This file is subject to the terms and conditions of the GNU General Public
 * License.  See the file "COPYING" in the main directory of this archive
 * for more details.
 *
 * Copyright (C) 2019 Kalray Inc.
 */

#ifndef KVX_ETH_TX_REGS_H
#define KVX_ETH_TX_REGS_H



/* group MPPA_ETHERNET_TX_CBS */
#define KVX_ETH_TX_CBS_GRP_OFFSET                  0x2D8
#define KVX_ETH_TX_CBS_GRP_ELEM_SIZE               0xB4
#define KVX_ETH_TX_CBS_GRP_ELEM_NB                 0x4
#define KVX_ETH_TX_CBS_CBS_ENABLE_OFFSET           0x0
#define KVX_ETH_TX_CBS_CBS_ENABLE_ELEM_SIZE        0x4
#define KVX_ETH_TX_CBS_CBS_ENABLE_ELEM_NB          0x9
#define KVX_ETH_TX_CBS_IDLE_SLOPE_OFFSET           0x24
#define KVX_ETH_TX_CBS_IDLE_SLOPE_ELEM_SIZE        0x4
#define KVX_ETH_TX_CBS_IDLE_SLOPE_ELEM_NB          0x9
#define KVX_ETH_TX_CBS_SEND_SLOPE_OFFSET           0x48
#define KVX_ETH_TX_CBS_SEND_SLOPE_ELEM_SIZE        0x4
#define KVX_ETH_TX_CBS_SEND_SLOPE_ELEM_NB          0x9
#define KVX_ETH_TX_CBS_THRESHOLD_OFFSET            0x6C
#define KVX_ETH_TX_CBS_THRESHOLD_ELEM_SIZE         0x4
#define KVX_ETH_TX_CBS_THRESHOLD_ELEM_NB           0x9
#define KVX_ETH_TX_CBS_MAX_CREDIT_OFFSET           0x90
#define KVX_ETH_TX_CBS_MAX_CREDIT_ELEM_SIZE        0x4
#define KVX_ETH_TX_CBS_MAX_CREDIT_ELEM_NB          0x9

/* group MPPA_ETHERNET_TX_CREDIT */
#define KVX_ETH_TX_CREDIT_GRP_OFFSET               0x4
#define KVX_ETH_TX_CREDIT_ENABLE_OFFSET            0x0

/* group MPPA_ETHERNET_TX_EXP_NPRE */
#define KVX_ETH_TX_EXP_NPRE_GRP_OFFSET             0x1028
#define KVX_ETH_TX_EXP_NPRE_GRP_ELEM_SIZE          0x4
#define KVX_ETH_TX_EXP_NPRE_GRP_ELEM_NB            0x4
#define KVX_ETH_TX_EXP_NPRE_CONFIG_OFFSET          0x0

/* group MPPA_ETHERNET_TX_ICRC_MASK */
#define KVX_ETH_TX_ICRC_MASK_GRP_OFFSET            0x2A8
#define KVX_ETH_TX_ICRC_MASK_ROCEV2_IPV6_OFFSET    0x0
#define KVX_ETH_TX_ICRC_MASK_ROCEV2_IPV6_ELEM_SIZE 0x4
#define KVX_ETH_TX_ICRC_MASK_ROCEV2_IPV6_ELEM_NB   0x4
#define KVX_ETH_TX_ICRC_MASK_ROCEV2_IPV4_OFFSET    0x10
#define KVX_ETH_TX_ICRC_MASK_ROCEV2_IPV4_ELEM_SIZE 0x4
#define KVX_ETH_TX_ICRC_MASK_ROCEV2_IPV4_ELEM_NB   0x4
#define KVX_ETH_TX_ICRC_MASK_ROCEV1_OFFSET         0x20
#define KVX_ETH_TX_ICRC_MASK_ROCEV1_ELEM_SIZE      0x4
#define KVX_ETH_TX_ICRC_MASK_ROCEV1_ELEM_NB        0x4

/* group MPPA_ETHERNET_TX_PBDWRR */
#define KVX_ETH_TX_PBDWRR_GRP_OFFSET               0xE58
#define KVX_ETH_TX_PBDWRR_GRP_ELEM_SIZE            0x50
#define KVX_ETH_TX_PBDWRR_GRP_ELEM_NB              0x4
#define KVX_ETH_TX_PBDWRR_CONFIG_OFFSET            0x0
#define KVX_ETH_TX_PBDWRR_INIT_QUANTUM_OFFSET      0x4
#define KVX_ETH_TX_PBDWRR_QUANTUM_OFFSET           0x8
#define KVX_ETH_TX_PBDWRR_QUANTUM_ELEM_SIZE        0x4
#define KVX_ETH_TX_PBDWRR_QUANTUM_ELEM_NB          0x9
#define KVX_ETH_TX_PBDWRR_PRIORITY_OFFSET          0x2C
#define KVX_ETH_TX_PBDWRR_PRIORITY_ELEM_SIZE       0x4
#define KVX_ETH_TX_PBDWRR_PRIORITY_ELEM_NB         0x9

/* group MPPA_ETHERNET_TX_PBRR */
#define KVX_ETH_TX_PBRR_GRP_OFFSET                 0xF98
#define KVX_ETH_TX_PBRR_GRP_ELEM_SIZE              0x24
#define KVX_ETH_TX_PBRR_GRP_ELEM_NB                0x4
#define KVX_ETH_TX_PBRR_PRIORITY_OFFSET            0x0
#define KVX_ETH_TX_PBRR_PRIORITY_ELEM_SIZE         0x4
#define KVX_ETH_TX_PBRR_PRIORITY_ELEM_NB           0x9

/* group MPPA_ETHERNET_TX_PFC */
#define KVX_ETH_TX_PFC_GRP_OFFSET                  0xDC8
#define KVX_ETH_TX_PFC_GRP_ELEM_SIZE               0x24
#define KVX_ETH_TX_PFC_GRP_ELEM_NB                 0x4
#define KVX_ETH_TX_PFC_XOFF_SUBSCR_OFFSET          0x0
#define KVX_ETH_TX_PFC_XOFF_SUBSCR_ELEM_SIZE       0x4
#define KVX_ETH_TX_PFC_XOFF_SUBSCR_ELEM_NB         0x9
#define KVX_ETH_TX_PFC_XOFF_SUBSCR_XOFF_SUBSCR_SHIFT 0x0
#define KVX_ETH_TX_PFC_XOFF_SUBSCR_XOFF_SUBSCR_MASK 0xFFUL
#define KVX_ETH_TX_PFC_XOFF_SUBSCR_GLBL_PAUSE_SUBSCR_SHIFT 0x8
#define KVX_ETH_TX_PFC_XOFF_SUBSCR_GLBL_PAUSE_SUBSCR_MASK 0x100UL

/* group MPPA_ETHERNET_TX_PTP */
#define KVX_ETH_TX_PTP_GRP_OFFSET                  0x1044
#define KVX_ETH_TX_PTP_GRP_ELEM_SIZE               0x8C
#define KVX_ETH_TX_PTP_GRP_ELEM_NB                 0x4
#define KVX_ETH_TX_PTP_TSTAMP_HI_OFFSET            0x0
#define KVX_ETH_TX_PTP_TSTAMP_HI_ELEM_SIZE         0x4
#define KVX_ETH_TX_PTP_TSTAMP_HI_ELEM_NB           0x10
#define KVX_ETH_TX_PTP_TSTAMP_LO_OFFSET            0x40
#define KVX_ETH_TX_PTP_TSTAMP_LO_ELEM_SIZE         0x4
#define KVX_ETH_TX_PTP_TSTAMP_LO_ELEM_NB           0x10
#define KVX_ETH_TX_PTP_TSTAMP_VAL_OFFSET           0x80
#define KVX_ETH_TX_PTP_TSTAMP_VAL_LAC_OFFSET       0x84
#define KVX_ETH_TX_PTP_TSTAMP_VAL_IT_OFFSET        0x88

/* group MPPA_ETHERNET_TX_STAGE_ONE */
#define KVX_ETH_TX_STAGE_ONE_GRP_OFFSET            0x0
#define KVX_ETH_TX_STAGE_ONE_CONFIG_OFFSET         0x0

/* group MPPA_ETHERNET_TX_STAGE_TWO */
#define KVX_ETH_TX_STAGE_TWO_GRP_OFFSET            0x8
#define KVX_ETH_TX_STAGE_TWO_GRP_ELEM_SIZE         0xA8
#define KVX_ETH_TX_STAGE_TWO_GRP_ELEM_NB           0x4
#define KVX_ETH_TX_STAGE_TWO_DROP_DISABLE_OFFSET   0x0
#define KVX_ETH_TX_STAGE_TWO_DROP_DISABLE_SIZE_SHIFT 0x0
#define KVX_ETH_TX_STAGE_TWO_DROP_DISABLE_SIZE_MASK 0x1UL
#define KVX_ETH_TX_STAGE_TWO_DROP_DISABLE_CRC_SHIFT 0x1
#define KVX_ETH_TX_STAGE_TWO_DROP_DISABLE_CRC_MASK 0x2UL
#define KVX_ETH_TX_STAGE_TWO_DROP_DISABLE_PAR_SHIFT 0x2
#define KVX_ETH_TX_STAGE_TWO_DROP_DISABLE_PAR_MASK 0x4UL
#define KVX_ETH_TX_STAGE_TWO_DROP_DISABLE_MTU_SHIFT 0x3
#define KVX_ETH_TX_STAGE_TWO_DROP_DISABLE_MTU_MASK 0x8UL
#define KVX_ETH_TX_STAGE_TWO_MTU_OFFSET            0x4
#define KVX_ETH_TX_STAGE_TWO_DROP_CNT_MSK_OFFSET   0x8
#define KVX_ETH_TX_STAGE_TWO_DROP_CNT_MSK_SIZE_SHIFT 0x0
#define KVX_ETH_TX_STAGE_TWO_DROP_CNT_MSK_SIZE_MASK 0x1UL
#define KVX_ETH_TX_STAGE_TWO_DROP_CNT_MSK_CRC_SHIFT 0x1
#define KVX_ETH_TX_STAGE_TWO_DROP_CNT_MSK_CRC_MASK 0x2UL
#define KVX_ETH_TX_STAGE_TWO_DROP_CNT_MSK_PAR_SHIFT 0x2
#define KVX_ETH_TX_STAGE_TWO_DROP_CNT_MSK_PAR_MASK 0x4UL
#define KVX_ETH_TX_STAGE_TWO_DROP_CNT_MSK_MTU_SHIFT 0x3
#define KVX_ETH_TX_STAGE_TWO_DROP_CNT_MSK_MTU_MASK 0x8UL
#define KVX_ETH_TX_STAGE_TWO_DROP_CNT_SUBSCR_OFFSET 0xC
#define KVX_ETH_TX_STAGE_TWO_DROP_CNT_OFFSET       0x10
#define KVX_ETH_TX_STAGE_TWO_DROP_CNT_LAC_OFFSET   0x14
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_OFFSET    0x18
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_ELEM_SIZE 0x4
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_ELEM_NB   0x9
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_SIZE_SHIFT 0x0
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_SIZE_MASK 0x1UL
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_CRC_SHIFT 0x1
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_CRC_MASK  0x2UL
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_PAR_SHIFT 0x2
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_PAR_MASK  0x4UL
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_MTU_SHIFT 0x3
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_MTU_MASK  0x8UL
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_LAC_OFFSET 0x3C
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_LAC_ELEM_SIZE 0x4
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_LAC_ELEM_NB 0x9
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_LAC_SIZE_SHIFT 0x0
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_LAC_SIZE_MASK 0x1UL
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_LAC_CRC_SHIFT 0x1
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_LAC_CRC_MASK 0x2UL
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_LAC_PAR_SHIFT 0x2
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_LAC_PAR_MASK 0x4UL
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_LAC_MTU_SHIFT 0x3
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_LAC_MTU_MASK 0x8UL
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_IT_OFFSET 0x60
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_IT_ELEM_SIZE 0x4
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_IT_ELEM_NB 0x9
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_IT_SIZE_SHIFT 0x0
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_IT_SIZE_MASK 0x1UL
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_IT_CRC_SHIFT 0x1
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_IT_CRC_MASK 0x2UL
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_IT_PAR_SHIFT 0x2
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_IT_PAR_MASK 0x4UL
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_IT_MTU_SHIFT 0x3
#define KVX_ETH_TX_STAGE_TWO_DROP_STATUS_IT_MTU_MASK 0x8UL
#define KVX_ETH_TX_STAGE_TWO_WMARK_OFFSET          0x84
#define KVX_ETH_TX_STAGE_TWO_WMARK_ELEM_SIZE       0x4
#define KVX_ETH_TX_STAGE_TWO_WMARK_ELEM_NB         0x9

/* group MPPA_ETHERNET_TX_TAS */
#define KVX_ETH_TX_TAS_GRP_OFFSET                  0x5A8
#define KVX_ETH_TX_TAS_GRP_ELEM_SIZE               0x208
#define KVX_ETH_TX_TAS_GRP_ELEM_NB                 0x4
#define KVX_ETH_TX_TAS_TAS_ENABLE_OFFSET           0x0
#define KVX_ETH_TX_TAS_TAS_ENABLE_ELEM_SIZE        0x4
#define KVX_ETH_TX_TAS_TAS_ENABLE_ELEM_NB          0xA
#define KVX_ETH_TX_TAS_CONFIG_CHANGE_OFFSET        0x28
#define KVX_ETH_TX_TAS_CONFIG_CHANGE_ELEM_SIZE     0x4
#define KVX_ETH_TX_TAS_CONFIG_CHANGE_ELEM_NB       0xA
#define KVX_ETH_TX_TAS_DYNAMIC_MODE_OFFSET         0x50
#define KVX_ETH_TX_TAS_DYNAMIC_MODE_ELEM_SIZE      0x4
#define KVX_ETH_TX_TAS_DYNAMIC_MODE_ELEM_NB        0xA
#define KVX_ETH_TX_TAS_WRITE_ENABLE_OFFSET         0x78
#define KVX_ETH_TX_TAS_WRITE_ENABLE_ELEM_SIZE      0x4
#define KVX_ETH_TX_TAS_WRITE_ENABLE_ELEM_NB        0xA
#define KVX_ETH_TX_TAS_LIST_LENGTH_OFFSET          0xA0
#define KVX_ETH_TX_TAS_LIST_LENGTH_ELEM_SIZE       0x4
#define KVX_ETH_TX_TAS_LIST_LENGTH_ELEM_NB         0xA
#define KVX_ETH_TX_TAS_ADDRESS_LIST_OFFSET         0xC8
#define KVX_ETH_TX_TAS_ADDRESS_LIST_ELEM_SIZE      0x4
#define KVX_ETH_TX_TAS_ADDRESS_LIST_ELEM_NB        0xA
#define KVX_ETH_TX_TAS_START_TIME_OFFSET           0xF0
#define KVX_ETH_TX_TAS_START_TIME_ELEM_SIZE        0x4
#define KVX_ETH_TX_TAS_START_TIME_ELEM_NB          0xA
#define KVX_ETH_TX_TAS_END_TIME_OFFSET             0x118
#define KVX_ETH_TX_TAS_END_TIME_ELEM_SIZE          0x4
#define KVX_ETH_TX_TAS_END_TIME_ELEM_NB            0xA
#define KVX_ETH_TX_TAS_START_POINT_OFFSET          0x140
#define KVX_ETH_TX_TAS_START_POINT_ELEM_SIZE       0x4
#define KVX_ETH_TX_TAS_START_POINT_ELEM_NB         0xA
#define KVX_ETH_TX_TAS_MAX_CYCLE_PHASE_OFFSET      0x168
#define KVX_ETH_TX_TAS_MAX_CYCLE_PHASE_ELEM_SIZE   0x4
#define KVX_ETH_TX_TAS_MAX_CYCLE_PHASE_ELEM_NB     0xA
#define KVX_ETH_TX_TAS_RATE_FACTOR_OFFSET          0x190
#define KVX_ETH_TX_TAS_RATE_FACTOR_ELEM_SIZE       0x4
#define KVX_ETH_TX_TAS_RATE_FACTOR_ELEM_NB         0xA
#define KVX_ETH_TX_TAS_RATE_SHIFT_OFFSET           0x1B8
#define KVX_ETH_TX_TAS_RATE_SHIFT_ELEM_SIZE        0x4
#define KVX_ETH_TX_TAS_RATE_SHIFT_ELEM_NB          0xA
#define KVX_ETH_TX_TAS_FORCE_SCHEDULING_OFFSET     0x1E0
#define KVX_ETH_TX_TAS_FORCE_SCHEDULING_ELEM_SIZE  0x4
#define KVX_ETH_TX_TAS_FORCE_SCHEDULING_ELEM_NB    0xA

/* group MPPA_ETHERNET_TX_TDM */
#define KVX_ETH_TX_TDM_GRP_OFFSET                  0x1038
#define KVX_ETH_TX_TDM_CONFIG_OFFSET               0x0
#define KVX_ETH_TX_TDM_FCS_OFFSET                  0x4
#define KVX_ETH_TX_TDM_FCS_PREEMTABLE_SHIFT        0x0
#define KVX_ETH_TX_TDM_FCS_PREEMTABLE_MASK         0xFUL
#define KVX_ETH_TX_TDM_FCS_EXPRESS_SHIFT           0x4
#define KVX_ETH_TX_TDM_FCS_EXPRESS_MASK            0xF0UL
#define KVX_ETH_TX_TDM_ERR_OFFSET                  0x8
#define KVX_ETH_TX_TDM_ERR_PREEMTABLE_SHIFT        0x0
#define KVX_ETH_TX_TDM_ERR_PREEMTABLE_MASK         0xFUL
#define KVX_ETH_TX_TDM_ERR_EXPRESS_SHIFT           0x4
#define KVX_ETH_TX_TDM_ERR_EXPRESS_MASK            0xF0UL

#endif /* KVX_ETH_TX_REGS_H */
